// Career predictions, 68 entries
// Tone: sharp, behaviorally grounded. Avoids generic motivation.
// Each has: teaser (hook), full (depth), action (concrete step), timing (hint), shareSnippet (share text).

export const career = [
 {
 id: 'C001',
 teaser: 'You will be put on the spot today, before you feel fully ready.',
 full: 'A question, a request, or a moment will arrive where a response is expected immediately. The instinct will be to defer or hedge. Neither will serve you. What comes out under pressure often turns out to be accurate enough.',
 action: 'When it happens, answer with what you actually think, not the most diplomatic version.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'You will be put on the spot today before you feel ready. What comes out under pressure is often accurate enough.',
 },
 {
 id: 'C002',
 teaser: 'Something you\'ve been putting off will come looking for you today.',
 full: 'It won\'t wait anymore. The conversation, the task, the decision, whatever it is, will surface itself. The timing won\'t be yours to choose. Whether you\'re ready or not, it\'s arriving today.',
 action: 'Get ahead of it in the first two hours if you can. On your terms is better than theirs.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Something you\'ve been putting off will come looking for you today. Get ahead of it if you can.',
 },
 {
 id: 'C003',
 teaser: 'An unexpected ask from someone senior will land today.',
 full: 'It will come through a meeting, a message, or a brief exchange. The ask will be bigger than the format suggests. How you respond in the first 60 seconds matters more than the full response you give later.',
 action: 'Buy yourself thinking time with a confident acknowledgment, then deliver a considered answer.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'An unexpected ask from someone senior will land today. The first 60 seconds sets the tone.',
 },
 {
 id: 'C004',
 teaser: 'Someone will notice what you\'ve been doing. The audience won\'t be who you expected.',
 full: 'Visibility will come from unexpected angles. Someone you weren\'t performing for has been watching. The attention will arrive in some form today, a mention, a reference, a direct acknowledgment.',
 action: 'Don\'t minimize it when it comes. Receive it cleanly.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'Someone will notice what you\'ve been doing today. The audience was never who you expected.',
 },
 {
 id: 'C005',
 teaser: 'A decision you thought was settled will get reopened today.',
 full: 'Something that felt closed, agreed, filed, done, will get pulled back out. Someone has a new angle, new information, or changed their mind. Frustrating as it is, the reopening will be useful.',
 action: 'Approach it with fresh eyes instead of defending the original position.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'A decision you thought was settled will get reopened today. The second look will be useful.',
 },
 {
 id: 'C006',
 teaser: 'You\'ll need to speak up about something today, and the timing will feel off.',
 full: 'There will be a moment where something should be said, a concern, a correction, a piece of information the room doesn\'t have. The moment won\'t feel convenient. It never does.',
 action: 'Say it anyway. The moment passes permanently.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'You\'ll need to speak up about something today. The timing won\'t feel right. Say it anyway.',
 },
 {
 id: 'C007',
 teaser: 'Something you built or delivered weeks ago will resurface in a conversation today.',
 full: 'Past work comes back in two directions, either it earns you something, or it creates a conversation you weren\'t expecting. Today it resurfaces. The quality of what you delivered then is the quality of what speaks for you now.',
 action: 'Review it briefly before any meeting today in case it comes up.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'Something you built weeks ago will resurface today. The quality of past work is what speaks for you now.',
 },
 {
 id: 'C008',
 teaser: 'You\'ll have to deliver something today before you feel fully ready.',
 full: 'The timing is not going to improve. Waiting for a better moment means this either gets done now under pressure or misses its window entirely. Ready enough is the correct standard here.',
 action: 'Ship the imperfect version. The feedback will make it better faster than more preparation would have.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'You\'ll have to deliver something today before you feel fully ready. Ready enough is the correct standard.',
 },
 {
 id: 'C009',
 teaser: 'An opportunity will appear today with a shorter window than you\'d prefer.',
 full: 'It will have a visible expiration. Something opens up, a gap, a request, an unexpected invitation, and the hesitation window is measurably narrow. Deciding slowly here is the same as deciding no.',
 action: 'When it appears, give yourself 10 minutes to decide. Don\'t carry it past today.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'An opportunity will appear today with a shorter window than you\'d prefer. Slow is no.',
 },
 {
 id: 'C010',
 teaser: 'A conversation about your role or direction will happen unexpectedly today.',
 full: 'Not a formal review, more like an informal exchange that becomes real quickly. Someone will ask a direct question about what you want or where you\'re headed. Having an honest answer matters more than a polished one.',
 action: 'Know what your honest answer is before the day begins.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'A conversation about your direction will happen unexpectedly today. Your honest answer matters more than a polished one.',
 },
 {
 id: 'C011',
 teaser: 'Someone will make an assumption about your capacity today that isn\'t accurate.',
 full: 'They\'ll assign you something, or not assign you something, based on a read of you that\'s out of date or just incorrect. You can accept the assumption or correct it. Accepting it quietly will make it permanent.',
 action: 'Correct the assumption the moment you notice it.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Someone will make an assumption about your capacity today that isn\'t accurate. Correct it immediately.',
 },
 {
 id: 'C012',
 teaser: 'A gap in something you delivered will surface today.',
 full: 'Something you thought was complete enough will be looked at more closely. A question will come in, or a gap will be pointed out. This isn\'t a failure, it\'s an opportunity to respond well under scrutiny.',
 action: 'Address it quickly and without defensiveness. The recovery is what people remember.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'A gap in something you delivered will surface today. The recovery is what people remember.',
 },
 {
 id: 'C013',
 teaser: 'Someone you will have underestimated will surprise you today.',
 full: 'A person you categorized, as less capable, less invested, or less relevant, will do something that doesn\'t fit the category. It\'s worth updating your model rather than explaining it away.',
 action: 'Let the surprise revise your read of them. The old model was costing you something.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'Someone you will have underestimated will surprise you today. Let it revise your model.',
 },
 {
 id: 'C014',
 teaser: 'A move you\'ve been delaying will have a narrowing window from here.',
 full: 'The circumstances that make this move viable are not going to stay static. Something is changing, people are leaving, priorities are shifting, the window is closing. The urgency isn\'t artificial.',
 action: 'Take one concrete step toward this today. Not next week.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'A move you\'ve been delaying will have a narrowing window from here. One step, today.',
 },
 {
 id: 'C015',
 teaser: 'Someone has been taking credit for something adjacent to your work. Today pushes it further.',
 full: 'There\'s been a gradual pattern of something yours being attributed elsewhere. Today something happens that makes the attribution more visible, more public, or more entrenched. It\'s easier to correct now than later.',
 action: 'Establish clear authorship today, in writing if possible.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'Someone has been taking credit for something adjacent to your work. Establish authorship today.',
 },
 {
 id: 'C016',
 teaser: 'Your current pace will hit its wall this week if nothing changes.',
 full: 'The load is above what can be sustained at this quality level. Something will slip, not because you don\'t care, but because physics. The time to adjust is before the slip, not after.',
 action: 'Remove one thing from this week\'s plate. Not tomorrow.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'Your current pace will hit its wall this week. The time to adjust is before something slips, not after.',
 },
 {
 id: 'C017',
 teaser: 'A skill gap you\'ve been navigating around is about to become visible.',
 full: 'You\'ve been routing around it, delegating the part you don\'t know, avoiding situations where it would show up. Something today will bring it closer to the surface than your usual workarounds can manage.',
 action: 'Spend 30 minutes doing something about it directly today.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A skill gap you\'ve been navigating around is about to become visible. Address it before it shows up.',
 },
 {
 id: 'C018',
 teaser: 'The answer you\'ve been circling is available, you just haven\'t asked the question.',
 full: 'You\'ve been reasoning around this for longer than necessary. The information exists, with a person, in a document, in an obvious place you haven\'t checked. The gap is a conversation, not a knowledge problem.',
 action: 'Ask the question today. Directly.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'The answer you\'ve been circling is available. You just haven\'t asked the question yet.',
 },
 {
 id: 'C019',
 teaser: 'The first two hours of your morning today will set the tone for the rest of the day.',
 full: 'Not metaphorically, literally. What you do in the window before the day fills with other people\'s agendas determines how the day lands. Starting on your terms produces measurably different outcomes than starting on incoming.',
 action: 'Do your most important thing first, before email or messages.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'The first two hours of your morning will set the tone for the rest of the day. Start on your terms.',
 },
 {
 id: 'C020',
 teaser: 'Someone is waiting on something from you. Their patience is not as intact as you\'re assuming.',
 full: 'There\'s a deliverable, a response, or a decision they\'re holding for. They haven\'t pushed, yet. But the gap between “they haven\'t said anything” and “they\'re fine” is wider than you\'re tracking.',
 action: 'Give them a clear update or delivery today.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'Someone is waiting on something from you. Their patience is not as intact as you\'re assuming.',
 },
 {
 id: 'C021',
 teaser: 'Your reputation is slightly ahead of where your work currently is.',
 full: 'There\'s a gap forming between the expectation you\'ve set and the output you\'re currently delivering. Most people can\'t see it yet. But the gap doesn\'t close by itself, and the longer it grows the harder the correction.',
 action: 'Choose one piece of work today and take it to a higher standard.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'Your reputation is slightly ahead of your current output. The gap doesn\'t close on its own.',
 },
 {
 id: 'C022',
 teaser: 'A decision you\'ve been deferring will be made by default if you wait much longer.',
 full: 'Situations move forward whether you decide or not. What you\'re treating as a pause is actually an abdication, the decision will be made, just not by you. Letting it happen by default usually means worse outcomes than choosing.',
 action: 'Make the call today. Imperfect is fine.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'A decision you\'ve been deferring will be made by default if you wait. Imperfect and chosen beats perfect and missed.',
 },
 {
 id: 'C023',
 teaser: 'The project in your head is better than the one currently underway. Today is why.',
 full: 'Something will happen today, a meeting, a deliverable, an exchange, that will show you exactly where the current execution has drifted from the intent. The drift is correctable, but someone has to name it.',
 action: 'Realign execution to the original intent in one visible way today.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'The project in your head is better than the one underway. The drift is correctable if someone names it.',
 },
 {
 id: 'C024',
 teaser: 'Someone who has been underestimating you will see something different today.',
 full: 'They had a limited read of you, based on one piece of work, one interaction, or a second-hand impression. Today you\'ll do something, say something, or be present in a way that doesn\'t fit that model.',
 action: 'Do the work at the level you\'re actually capable of. Let it speak.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'Someone who has been underestimating you will see something different today. Let the work speak.',
 },
 {
 id: 'C025',
 teaser: 'A professional relationship that has gone quiet will require attention soon.',
 full: 'A connection you\'ve let drift to low maintenance is about to need something, from you or from it. Either way, the dormancy is about to end. The question is whether you reach out first or get reached.',
 action: 'Reach out before they have to.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A professional relationship that has gone quiet will require attention soon. Reach out before they have to.',
 },
 {
 id: 'C026',
 teaser: 'A request will land today that you should say no to but won\'t want to.',
 full: 'The request will be reasonable, maybe even flattering. Saying yes is the easier path. But you know your current capacity, and this doesn\'t fit without something else slipping.',
 action: 'Say no with a specific reason. The reason makes it final.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'A request will land today that you should say no to. Your current capacity is the honest answer.',
 },
 {
 id: 'C027',
 teaser: 'The way you\'re working is producing the ceiling, not the effort level.',
 full: 'You can work harder and get roughly the same results because the structure is the constraint, not the intensity. More effort into a limited system produces diminishing returns. Something structural needs to change.',
 action: 'Identify one habit or process that\'s creating your ceiling. Change that, not your hours.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'The way you\'re working is producing the ceiling, not the effort level. Change the structure.',
 },
 {
 id: 'C028',
 teaser: 'An early draft needs to leave your hands today, not next week.',
 full: 'You\'re improving it in private when the feedback loop would do more good than the additional self-editing. The iteration starts when it leaves the room. Private improvement has a ceiling that feedback doesn\'t.',
 action: 'Send it today in current form with a note that it\'s early stage.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'An early draft needs to leave your hands today. The iteration starts when it leaves the room.',
 },
 {
 id: 'C029',
 teaser: 'Ambiguity in a current scope will cause a larger problem next week if you leave it.',
 full: 'Two parties are operating on different assumptions about what\'s expected. Both have accepted the ambiguity because naming it feels awkward. It will surface eventually, better on your terms than someone else\'s.',
 action: 'Clarify one assumption in writing today.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'Ambiguity in a current scope will cause a larger problem next week. Clarify it today on your terms.',
 },
 {
 id: 'C030',
 teaser: 'You\'ll find yourself measuring against someone whose output doesn\'t reflect their actual position.',
 full: 'The comparison will be misleading, you\'ll be benchmarking against their visible surface, which doesn\'t show what\'s actually underneath their numbers. You\'re comparing your behind-the-scenes to their front-of-house.',
 action: 'Stop measuring against this person. Measure against your own last position.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'The comparison you\'re making measures the wrong things. Your behind-the-scenes vs. their front-of-house.',
 },
 {
 id: 'C031',
 teaser: 'Visibility of your work is lower than the quality of your work today.',
 full: 'There\'s a gap between how good the work actually is and how well it\'s being seen by the people who matter. Quality alone doesn\'t surface in most environments. Someone needs to surface it.',
 action: 'Communicate one piece of your work explicitly to someone who should know about it.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'Visibility of your work is lower than the quality. Quality alone doesn\'t surface. Surface it yourself.',
 },
 {
 id: 'C032',
 teaser: 'A meeting today carries more weight than the calendar suggests.',
 full: 'The title is routine but the stakes aren\'t. A decision is likely to be made informally, or an impression is going to form that lasts longer than the meeting itself. Showing up unprepared here is a real cost.',
 action: 'Prepare one concrete point you want to make before you walk in.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'A meeting today carries more weight than the calendar suggests. Decisions are made informally.',
 },
 {
 id: 'C033',
 teaser: 'You already know the right call. More deliberation isn\'t changing the answer.',
 full: 'The analysis has run past its useful endpoint. The data is in, the instinct is clear, and additional deliberation is functioning as delay rather than diligence. You\'re waiting for certainty that isn\'t coming.',
 action: 'Make the call today.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'You already know the right call. More deliberation isn\'t changing the answer. Make it today.',
 },
 {
 id: 'C034',
 teaser: 'Deep, uninterrupted work today will produce more than anything in your meeting schedule.',
 full: 'The calendar is full, but the meetings aren\'t where the high-leverage work happens. The thing that actually moves your position needs two uninterrupted hours to take shape. It cannot happen 20 minutes at a time.',
 action: 'Block and protect two hours for deep work today.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Deep work today has higher return than anything in your meeting schedule. Block the time.',
 },
 {
 id: 'C035',
 teaser: 'Someone needs clearer direction from you and hasn\'t been able to ask for it.',
 full: 'They\'re moving forward with assumptions because the explicit direction wasn\'t given. This isn\'t their failure, it\'s a gap in what was communicated. The ambiguity from your side is creating slow-moving cost on theirs.',
 action: 'Proactively provide direction before they have to stop and ask.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Someone needs clearer direction from you and hasn\'t been able to ask for it.',
 },
 {
 id: 'C036',
 teaser: 'You\'re being visibly busy in a way that isn\'t building toward anything.',
 full: 'The activity looks like progress. The calendar is full, the messages are moving. But the score at the end of this week will look like last week\'s. Busy and productive have separated somewhere in the last few days.',
 action: 'Name the one thing that would actually move something. Do that before anything else today.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'You\'re being visibly busy in a way that isn\'t building toward anything. Busy and productive have separated.',
 },
 {
 id: 'C037',
 teaser: 'A peer\'s observation from recently is more useful than you treated it at the time.',
 full: 'Someone said something that didn\'t land well in the moment, a critique, a comparison, an uncomfortable truth. You deflected or minimized it. The accurate part of it is still sitting there.',
 action: 'Revisit it without the defensiveness and extract the useful part.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'A peer\'s observation from recently is more useful than you treated it. The accurate part is still there.',
 },
 {
 id: 'C038',
 teaser: 'Something in your current environment is keeping your baseline lower than it should be.',
 full: 'The standard of what\'s normal around you has been calibrated to a level that doesn\'t match your actual capacity. You\'ve adapted to what\'s expected here and called it normal. It isn\'t your ceiling.',
 action: 'Ask honestly: is this environment raising or constraining your standard?',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'Something in your current environment is keeping your baseline lower than it should be.',
 },
 {
 id: 'C039',
 teaser: 'A creative block will clear if you produce something today, not if you wait.',
 full: 'The block doesn\'t end when conditions improve. It ends when you produce something, even bad, even rough. Output generates momentum that thinking about output never does.',
 action: 'Produce something today. Low quality is fine. Moving is the only metric.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'A creative block clears when you produce something, not when you wait for the right moment.',
 },
 {
 id: 'C040',
 teaser: 'Someone in a position to influence your trajectory is forming an opinion about your work right now.',
 full: 'There\'s a window where a decision-maker or influential person is looking at something in your orbit, your work, your behavior, your outputs. The impression formed in this window has a longer half-life than usual.',
 action: 'Make what\'s visible today representative of your actual standard.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'Someone who can influence your trajectory is forming an opinion right now. Make what\'s visible count.',
 },
 {
 id: 'C041',
 teaser: 'The plan is agreed upon. Today requires the first real act of execution.',
 full: 'The conversations have happened. The plan is aligned. What has consistently not happened is the first concrete action that turns intent into movement. Execution doesn\'t start at the planning table.',
 action: 'Do one concrete act today that is execution, not discussion.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'The plan is agreed upon. Today requires the first real act of execution. Talking about it doesn\'t count.',
 },
 {
 id: 'C042',
 teaser: 'You\'re operating below your actual level to avoid disrupting the room\'s comfort.',
 full: 'There\'s a version of you that would push harder, ask for more, or challenge what\'s going unquestioned. You\'ve dialed it back to fit the room. That calibration is costing you output and, over time, positioning.',
 action: 'Push to your actual level in one area today.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'You\'re operating below your actual level to avoid friction. That calibration has a real cost.',
 },
 {
 id: 'C043',
 teaser: 'A project you\'ve been treating as secondary is shaping how people think about you.',
 full: 'You\'ve been directing your energy toward what feels more important. But the people this secondary project touches have a broader view of your work than you realize. Their opinion is forming from it regardless.',
 action: 'Give it the quality it deserves, not the attention it feels like it deserves.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'A project you\'ve been treating as secondary is shaping your reputation more than you know.',
 },
 {
 id: 'C044',
 teaser: 'The difficulty you\'re experiencing is positional, not directional.',
 full: 'The resistance you\'re hitting isn\'t evidence that you\'re heading the wrong way. It\'s the predictable friction that comes with being in a specific part of the process. Going through it is the path forward.',
 action: 'Keep going. Don\'t change direction based on difficulty alone.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'The difficulty you\'re experiencing is positional, not directional. The resistance isn\'t a signal to stop.',
 },
 {
 id: 'C045',
 teaser: 'One good question asked of the right person today will do more than another month of independent solving.',
 full: 'You\'ve been approaching this as a problem to solve alone. It isn\'t. The information exists somewhere outside your own reasoning, with a person, in an accessible place you haven\'t gone. The bottleneck is a conversation, not more thinking.',
 action: 'Identify the right person and ask the question today.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'One good question to the right person will do more than another month of solving in isolation.',
 },
 {
 id: 'C046',
 teaser: 'You\'re in the right place but the wrong function today.',
 full: 'The environment works, the context is right, the people are aligned, but what you\'re spending your time on is constraining the output you\'re actually capable of. The place is fine. The specific task allocation isn\'t.',
 action: 'Identify where your highest leverage is and redirect some time there.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'You\'re in the right place but the wrong function. The environment is fine, the task allocation isn\'t.',
 },
 {
 id: 'C047',
 teaser: 'Moving fast on this one will create more work than moving carefully.',
 full: 'The urgency feels real but the cost of speed here will exceed the cost of time. A rushed version of this particular thing creates downstream work that a careful version wouldn\'t.',
 action: 'Slow down specifically on this. Push the timeline if needed.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'Moving fast on this one creates more work than moving carefully. Slow is right here.',
 },
 {
 id: 'C048',
 teaser: 'Recognition you\'ve been expecting hasn\'t arrived. Don\'t let it erode the work.',
 full: 'The acknowledgment was warranted and is delayed. That gap is real and worth noting. But the response to it can\'t be letting the quality slip retroactively. The work was good. Keep that true.',
 action: 'Make sure the right person knows about the work, once, directly.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'Recognition you\'ve been expecting hasn\'t arrived. Make sure the right person knows about the work.',
 },
 {
 id: 'C049',
 teaser: 'The problem is less complex than the conversation around it has become.',
 full: 'The discussion about this has taken on a life beyond the actual problem. Multiple stakeholders, multiple framings, compounding complexity. Someone needs to simplify the frame before the conversation becomes the problem.',
 action: 'State the core issue in one sentence. Bring it back to that.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'The problem is less complex than the conversation around it has become. Someone needs to simplify the frame.',
 },
 {
 id: 'C050',
 teaser: 'Something murky will clarify in the next few hours, not in the next few weeks.',
 full: 'You\'ve been waiting on clarity that keeps feeling like it\'s further away than it is. The fog is close to lifting, not from outside information arriving, but from the processing finishing. Don\'t make the decision before it clears.',
 action: 'Wait for the clarity window before acting. When it comes, move quickly.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Something murky will clarify in the next few hours. Wait for the window, then move.',
 },
 {
 id: 'C051',
 teaser: 'What you\'re calling perfectionism is also called not shipping.',
 full: 'The standard has passed its point of useful function and is now operating as a delay mechanism. The thing is ninety percent done, and the remaining ten percent is providing more psychological protection than quality improvement.',
 action: 'Ship it today. The feedback will improve it faster than more preparation will.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'What you\'re calling perfectionism is also called not shipping. The remaining polish is protection, not quality.',
 },
 {
 id: 'C052',
 teaser: 'Something you did on instinct will turn out to have been the right call.',
 full: 'A decision you made without complete information, one that felt uncertain or even reckless at the time, will be vindicated. The instinct was calibrated better than the analysis that came after it.',
 action: 'Trust the instinct that\'s currently in question. It\'s right.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'Something you did on instinct will turn out to have been the right call. The instinct was calibrated better than the analysis.',
 },
 {
 id: 'C053',
 teaser: 'A meeting will run long today because no one wants to make the actual decision.',
 full: 'The conversation will circle. Each lap will introduce one more consideration. The room is performing thoughtfulness while quietly hoping someone else will commit. The decision is yours to take if you want it.',
 action: 'Be the person who proposes the call out loud. The room will follow if it\'s reasonable.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'A meeting will run long today because no one wants to make the call. Be the person who does.',
 },
 {
 id: 'C054',
 teaser: 'You will be asked for your opinion today on something you actually have a strong view about.',
 full: 'The temptation will be to soften it down to a corporate-friendly version. The interesting answer is the unsoftened one. The diplomatic version is forgotten by lunch. The honest version is remembered next quarter.',
 action: 'Give the considered version of your real opinion. Diplomatic, not generic.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'You will be asked your opinion today on something you have a strong view about. Give the real one, considered.',
 },
 {
 id: 'C055',
 teaser: 'A small thing on your task list will turn out to be much bigger than its title suggested.',
 full: 'You scoped it casually. The actual work will be three layers deeper. Discovering the real shape will take half the day. The estimate was wrong because the framing was wrong, not because you misjudged.',
 action: 'Stop and re-scope before you keep grinding. Honest re-estimate beats heroic execution.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A small task today will turn out much bigger than its title suggested. Re-scope before you grind.',
 },
 {
 id: 'C056',
 teaser: 'Someone will copy your phrasing in a meeting today, almost certainly without realising.',
 full: 'A turn of phrase you used last week will reappear from someone else\'s mouth, framed as theirs. They\'re not stealing, they\'re absorbing. It means your language is shaping the room. That\'s leverage you should keep using.',
 action: 'Don\'t correct the attribution. Use a sharper version of the same phrase next time.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Someone will copy your phrasing in a meeting today. It means your language is shaping the room.',
 },
 {
 id: 'C057',
 teaser: 'A senior person will give you partial feedback today. The unsaid half is the important half.',
 full: 'They\'ll praise the surface, name one safe critique, and stop. The thing they didn\'t say is the thing you most need to hear. Their hesitation tells you where it is.',
 action: 'Ask one direct follow-up: "What is the thing you almost said and didn\'t?"',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'A senior person will give you partial feedback today. Ask: what did you almost say and not?',
 },
 {
 id: 'C058',
 teaser: 'You will spend more time today reading messages than doing the work the messages are about.',
 full: 'The notifications will feel productive while producing nothing. Each context switch will cost more than the message that caused it. By 3pm you\'ll feel busy and behind, which is the signature of this exact failure mode.',
 action: 'Pick the one task that matters and close every channel for the next 90 minutes. Just that.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'You will spend more time reading messages today than doing the work the messages are about. 90 minutes closed.',
 },
 {
 id: 'C059',
 teaser: 'A delay you have been blaming on someone else turns out to be partially yours today.',
 full: 'A piece of information they were waiting on, a clarification you assumed they had, a step that quietly stalled on your side. The blocker has had two contributors, not one. You\'ll see this clearly today.',
 action: 'Send the unblocking message before you assign more blame. Take the half that\'s yours.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'A delay you have been blaming on someone else turns out to be partially yours today.',
 },
 {
 id: 'C060',
 teaser: 'You will write a draft today that\'s much better than you give it credit for.',
 full: 'Whatever you produce, message, doc, deck, slide, will sit in your head as rough. Re-read it tomorrow and the rough version will be closer to right than your editing brain currently allows.',
 action: 'Send the version that exists. Don\'t take another pass for the sake of taking one.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'You will write a draft today that\'s better than you give it credit for. Send the version that exists.',
 },
 {
 id: 'C061',
 teaser: 'A peer will outshine you slightly today on something you both attempted.',
 full: 'The instinct will be to find the reason it doesn\'t count, the lucky angle, the unfair advantage. Resist the audit. The cleaner response is to look at what they actually did differently and learn it.',
 action: 'Ask them, briefly and without ego, how they approached it.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'A peer will outshine you slightly today. Ask them how. Resist the audit for the unfair angle.',
 },
 {
 id: 'C062',
 teaser: 'You will get a small win today and almost forget to notice it.',
 full: 'It will be modest, a thank-you, a passed test, a problem that resolved without escalation. The pace of the day will swallow it. Acknowledged wins compound. Unacknowledged wins evaporate.',
 action: 'Write the win down before the next task lands. One line is enough.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'You will get a small win today and almost forget to notice it. Acknowledged wins compound.',
 },
 {
 id: 'C063',
 teaser: 'A request will arrive today wrapped in urgency that isn\'t real.',
 full: 'The sender will frame it as time-critical because they want it off their plate. The actual deadline is later, sometimes much later. Treating their urgency as your emergency reorders your day for the wrong reason.',
 action: 'Ask once: "What is the actual hard deadline?" Then schedule based on that answer.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A request today will be wrapped in urgency that isn\'t real. Ask: what is the actual hard deadline?',
 },
 {
 id: 'C064',
 teaser: 'You will say yes to something today that you should have negotiated.',
 full: 'Scope, timing, ownership, all of it will be set by the asker, accepted by you, and locked in within the first thirty seconds. The shape of the work will be wrong before it starts.',
 action: 'Before you commit, ask one re-scoping question. Even a small one resets the frame.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'You will say yes today to something you should have negotiated. One question resets the frame.',
 },
 {
 id: 'C065',
 teaser: 'A piece of feedback you got recently will start making more sense by tonight.',
 full: 'It didn\'t land at the time. You filed it as unfair or off-base. A situation today will mirror what they were trying to say. The retroactive accuracy will be uncomfortable but useful.',
 action: 'Revisit the feedback in the new context. Update your read of the giver.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'A piece of feedback you got recently will start making more sense by tonight. Update your read.',
 },
 {
 id: 'C066',
 teaser: 'You will hesitate before pressing send on something today, and that hesitation is worth listening to.',
 full: 'The pause is not anxiety. It\'s pattern recognition catching something the conscious mind hasn\'t named yet. There\'s a phrasing issue, a missing recipient, an unconsidered audience. Re-read once before you send.',
 action: 'Trust the hesitation enough to do one slow pass. Send afterwards.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'You will hesitate before pressing send today. The pause is pattern recognition. One slow pass.',
 },
 {
 id: 'C067',
 teaser: 'A relationship at work that has been quietly cooling will need maintenance today.',
 full: 'You\'ll notice the shorter replies, the less generous interpretations, the slightly slower responses. None of it is dramatic. All of it is real. Five minutes of actual contact will reverse a month of drift.',
 action: 'Send a short, specific, unrelated-to-work message to that person today.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'A relationship at work that has been cooling will need maintenance today. Five minutes reverses a month.',
 },
 {
 id: 'C068',
 teaser: 'A piece of work you considered finished will reveal one more required step today.',
 full: 'You\'d closed the loop in your head. A small detail, surfaced by someone else or by your own re-read, will reopen it. The temptation is to ignore it. The cost of ignoring is bigger than the cost of doing it now.',
 action: 'Do the extra step the same day. Don\'t carry it over.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'A piece of work you considered finished will need one more step today. Don\'t carry it over.',
 },
];
