// Career predictions – 52 entries
// Tone: sharp, behaviorally grounded. Avoids generic motivation.
// Each has: teaser (hook), full (depth), action (concrete step), timing (hint), shareSnippet (share text).

export const career = [
  {
    id: 'C001',
    teaser: 'The thing you keep pushing to tomorrow is already two weeks late.',
    full: 'There is one task that has survived every daily list without getting done. It is not blocked by circumstances — it is blocked by something else. That something else is worth identifying.',
    action: 'Start it today. Not complete it — just start. The first ten minutes matter most.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'The task you keep pushing to tomorrow is already two weeks late. Ten minutes is all it takes.',
  },
  {
    id: 'C002',
    teaser: 'Someone at work is watching how you handle a current situation.',
    full: 'Your behavior right now is being noted by someone whose opinion will matter later. This is not paranoia — it is accurate. How you carry yourself in difficulty is the signal they are reading.',
    action: 'Act as if the right people are watching, because they are.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'Someone at work is watching how you handle this. Your behavior right now is being noted.',
  },
  {
    id: 'C003',
    teaser: 'An opportunity is visible but you keep calling it risk.',
    full: 'There is a move available to you that you have been framing as too uncertain. Part of you knows the framing is protecting you from a discomfort that is shorter than the cost of not moving.',
    action: 'Name the actual risk. Write it down. Then evaluate it as if someone else described it to you.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'An opportunity is available but you keep calling it risk. Name the actual risk and evaluate it clearly.',
  },
  {
    id: 'C004',
    teaser: 'You are overcommitted and it is starting to show in the quality of your work.',
    full: 'The volume of yes has exceeded the capacity to deliver well. Right now something is receiving the version of you that is running on low — not your best, not what you agreed to.',
    action: 'Identify one commitment you can reduce or push back. Do it before the end of the day.',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'You are overcommitted and it is starting to show in the quality of your work. Something has to give.',
  },
  {
    id: 'C005',
    teaser: 'A conversation with the right person could unlock the next three months.',
    full: 'There is someone in your network — or someone you could access — whose perspective or connection could cut through something you have been manually working around. You have not spoken to them recently.',
    action: 'Reach out to one person today who has knowledge or access you need.',
    timing: 'You will feel this most before you sleep.',
    shareSnippet: 'One conversation with the right person could unlock the next three months. You have not had it yet.',
  },
  {
    id: 'C006',
    teaser: 'You are working hard on the wrong thing.',
    full: 'Effort is present. Velocity is not. The task in front of you is a comfortable proxy for the thing that actually moves the needle. Busyness and progress are not the same thing right now.',
    action: 'Identify one action today that would have the highest actual impact, not the highest visibility.',
    timing: 'This shows up when you are least distracted.',
    shareSnippet: 'You are working hard on the wrong thing. Busyness and progress are not the same thing right now.',
  },
  {
    id: 'C007',
    teaser: 'Your idea will land better if you let someone else present part of it.',
    full: 'There is something you are approaching as a solo effort when it would gain more traction as a shared one. The credit math feels risky but the outcome math favors collaboration.',
    action: 'Bring in one ally before you present this.',
    timing: 'Notice this in the first conversation that matters today.',
    shareSnippet: 'Your idea will land better if you let someone else present part of it. The credit math is worth it.',
  },
  {
    id: 'C008',
    teaser: 'Something you built weeks ago is about to matter again.',
    full: 'A piece of work, a decision, a relationship — something you did earlier and moved past is about to resurface in a relevant context. The quality of that earlier work will speak for itself.',
    action: 'Review something you submitted or delivered recently. Is it as good as you remember?',
    timing: 'By tonight, this will be clearer.',
    shareSnippet: 'Something you built weeks ago is about to matter again. The quality of that earlier work will speak.',
  },
  {
    id: 'C009',
    teaser: 'The feedback you received last week is more accurate than it felt.',
    full: 'Your initial reaction was defensive — which is human. But now that the sting has faded, there is a real signal in what was said worth examining without the armor on.',
    action: 'Reread or revisit that feedback with fresh distance today.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'The feedback you received last week is more accurate than it felt. The sting has cleared. Look again.',
  },
  {
    id: 'C010',
    teaser: 'You are capable of more than your current environment is asking for.',
    full: 'The work is getting done but the ceiling here is lower than your actual level. You have been adapting to average because average is what gets rewarded in this particular context.',
    action: 'Do one thing today at the standard you are actually capable of, regardless of what is expected.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'You are capable of more than your current environment is asking for. The ceiling here is not yours.',
  },
  {
    id: 'C011',
    teaser: 'A conflict you have been smoothing over needs to be surfaced.',
    full: 'There is a tension at work that both parties are managing around rather than addressing. The management is using energy. The addressing would use less. But someone has to go first.',
    action: 'Name the issue, not the person. Focus on the work problem, not the interpersonal one.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'A conflict you have been smoothing over needs to surface. Managing it uses more energy than fixing it.',
  },
  {
    id: 'C012',
    teaser: 'You have more leverage in the current situation than you are using.',
    full: 'You are negotiating or operating from a position that is stronger than you are presenting. Either you do not see it, or discomfort with using it is making you smaller than the situation calls for.',
    action: 'Before your next important conversation, write down your actual position. Is it as weak as you are behaving?',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'You have more leverage in this situation than you are using. Your position is stronger than how you present it.',
  },
  {
    id: 'C013',
    teaser: 'The person you dismissed early has developed quickly.',
    full: 'Someone you categorized a while ago — junior, inexperienced, peripheral — has grown significantly. If you are still operating with the old model of them, you are working with inaccurate information.',
    action: 'Update your read on someone you have not paid real attention to recently.',
    timing: 'You will feel this most before you sleep.',
    shareSnippet: 'The person you dismissed a year ago has developed significantly. Your old model of them is inaccurate.',
  },
  {
    id: 'C014',
    teaser: 'Waiting for the perfect moment is the same as not going.',
    full: 'There is something you are qualified to do, propose, or raise — but you are waiting for conditions that are not going to materialize. The moment is now, imperfect as it is.',
    action: 'Make the move. Today.',
    timing: 'This shows up when you are least distracted.',
    shareSnippet: 'Waiting for the perfect moment is the same as not going. The conditions will not materialize.',
  },
  {
    id: 'C015',
    teaser: 'Someone is taking credit for something you did. You have not addressed it.',
    full: 'You noticed it. You told yourself it was not worth the friction. But the pattern has repeated and your visibility has suffered for it. Silence here is being read as agreement.',
    action: 'Establish authorship clearly in your next meeting or written communication. Not combatively — just accurately.',
    timing: 'Notice this in the first conversation that matters today.',
    shareSnippet: 'Someone is taking credit for your work. Your silence is being read as agreement. Establish authorship.',
  },
  {
    id: 'C016',
    teaser: 'Your current pace is unsustainable and you already know it.',
    full: 'You have been running at a level that requires things to go right every single day. They will not. You are one bad week away from a quality failure or a health cost. This is a warning, not a judgement.',
    action: 'Protect one hour today that is genuinely recovery, not deferred work.',
    timing: 'By tonight, this will be clearer.',
    shareSnippet: 'Your current pace is unsustainable. You are one bad week away from something breaking.',
  },
  {
    id: 'C017',
    teaser: 'A skill gap you have been hoping no one notices is about to become visible.',
    full: 'There is a competency area you have been navigating around — delegating, avoiding, or patching with confidence. Something upcoming will bring it closer to the surface.',
    action: 'Spend thirty minutes today working on the thing you have been avoiding.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'A skill gap you have been navigating around is about to become visible. Work on it today.',
  },
  {
    id: 'C018',
    teaser: 'The answer you are looking for is already available. You have not asked.',
    full: 'You are spending time reasoning around something that someone else has already solved or knows the answer to. The information gap is not knowledge — it is a conversation you have not had.',
    action: 'Ask the question you have been solving around. Today.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'The answer you are looking for is already available. You have just not asked the right person yet.',
  },
  {
    id: 'C019',
    teaser: 'Momentum is available today if you start before 11am.',
    full: 'Your first two hours of the workday have a disproportionate effect on the quality of the rest of it. What you do or avoid in that window sets the register for everything that follows.',
    action: 'Identify your one most important task and begin it before everything else.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'Momentum is available today if you start before 11am. What you do in the first two hours sets everything.',
  },
  {
    id: 'C020',
    teaser: 'Someone is frustrated by a delay that is on your side.',
    full: 'There is someone waiting on something from you — a decision, a response, a deliverable — and their patience is not as intact as you may be assuming. They have not pushed yet. They are close.',
    action: 'Identify who is waiting on you and give them a clear update today.',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'Someone is waiting on something from you and their patience is not as intact as you are assuming.',
  },
  {
    id: 'C021',
    teaser: 'Your reputation at work is ahead of your current output.',
    full: 'You have built credibility over time. Right now the work is not matching the reputation. This gap is not yet visible to most people — but it will widen if the current pace continues.',
    action: 'Pick one piece of work to sharpen to a higher standard today.',
    timing: 'You will feel this most before you sleep.',
    shareSnippet: 'Your reputation at work is ahead of your current output. That gap will widen if nothing changes.',
  },
  {
    id: 'C022',
    teaser: 'A decision you have been deferring will be made for you if you wait much longer.',
    full: 'There is a situation developing that will resolve itself by default if you do not intervene with your own choice. Default outcomes often favor the situational logic, not your actual preferences.',
    action: 'Make the decision today. Imperfect decision-making is better than no decision-making here.',
    timing: 'This shows up when you are least distracted.',
    shareSnippet: 'A decision you keep deferring will be made for you by default if you wait much longer.',
  },
  {
    id: 'C023',
    teaser: 'The version of this project in your head is better than the one underway.',
    full: 'There is a delta between how you envisioned this and how it is being executed — and part of the gap is you. Either you have not communicated the vision clearly or you have not protected it from compromise.',
    action: 'Realign the team or yourself to the original intent today.',
    timing: 'Notice this in the first conversation that matters today.',
    shareSnippet: 'The version of this project in your head is better than the one underway. You have not protected the vision.',
  },
  {
    id: 'C024',
    teaser: 'Someone is underestimating you and about to find out.',
    full: 'You are operating below what someone expects of you — either through their low estimation or through your own deliberate calibration. The gap between what they expect and what you can deliver is about to close.',
    action: 'Deliver one thing today that is above what was asked for.',
    timing: 'By tonight, this will be clearer.',
    shareSnippet: 'Someone is underestimating you and about to find out. Deliver something today that is above what was asked.',
  },
  {
    id: 'C025',
    teaser: 'A relationship at work has drifted and it matters more than you have treated it.',
    full: 'Someone you used to have regular meaningful exchanges with has faded into occasional polite contact. Relationships at work erode faster than personal ones when you stop actively maintaining them.',
    action: 'Schedule a real conversation with this person this week.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'A relationship at work has drifted and it matters more than you have treated it. Reach out.',
  },
  {
    id: 'C026',
    teaser: 'You are being asked to do too much and the answer should be no.',
    full: 'There is a request — or several — that would stretch you beyond useful capacity. The instinct to say yes comes from a real place. The cost of that yes will come from a real place too.',
    action: 'Say no to one thing today with a clear and respectful reason.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'You are being asked to do too much. The cost of yes will come from a real place. Say no to something.',
  },
  {
    id: 'C027',
    teaser: 'The stagnation you feel is not external — it is structural.',
    full: 'You are stuck not because circumstances are blocking you but because the way you are working is producing the same output regardless of effort. The structure needs to change, not the intensity.',
    action: 'Identify one process or habit that is creating the ceiling. Change it, not your effort level.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'The stagnation you feel is not external — it is structural. Change the structure, not the intensity.',
  },
  {
    id: 'C028',
    teaser: 'An early draft deserves to be shared before it is perfect.',
    full: 'You have something in progress that you are improving in private when you should be getting feedback. The perfectionism is protecting you from the work improving faster than you can improve it alone.',
    action: 'Share the draft. The iteration cycle starts when it leaves your hands.',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'An early draft deserves to be shared before it is perfect. Perfectionism is slowing the feedback loop.',
  },
  {
    id: 'C029',
    teaser: 'Clarity today will prevent a much more complicated conversation next week.',
    full: 'There is ambiguity in a current scope, expectation, or agreement. Both parties are operating on different assumptions. This will surface, and the later it surfaces the worse it is.',
    action: 'Clarify one assumption with one person today.',
    timing: 'You will feel this most before you sleep.',
    shareSnippet: 'Clarity today will prevent a much more complicated conversation next week. One assumption, one person.',
  },
  {
    id: 'C030',
    teaser: 'The comparison you are making is measuring the wrong variables.',
    full: 'You are benchmarking yourself against someone whose visible output does not reflect the actual trajectory of your work. You are comparing your behind-the-scenes to their highlights.',
    action: 'Stop the comparison. Measure your own progress against your own last position.',
    timing: 'This shows up when you are least distracted.',
    shareSnippet: 'The comparison you are making is measuring the wrong variables. Your work vs their highlights.',
  },
  {
    id: 'C031',
    teaser: 'You have been invisible in an environment that rewards visibility.',
    full: 'The work is good but the right people do not know it is yours. In many environments, quality alone does not surface. You have to surface it.',
    action: 'Communicate one piece of your work to someone who should know about it.',
    timing: 'Notice this in the first conversation that matters today.',
    shareSnippet: 'You have been invisible in an environment that rewards visibility. Quality alone does not surface.',
  },
  {
    id: 'C032',
    teaser: 'A meeting today is more important than it appears on the calendar.',
    full: 'There is a conversation today that carries more weight than its description suggests. Decisions may be made informally. Impressions may form that outlast the agenda.',
    action: 'Prepare something specific to say in it. Showing up without a point of view is missed opportunity.',
    timing: 'By tonight, this will be clearer.',
    shareSnippet: 'A meeting today is more important than it appears on the calendar. Decisions are made informally.',
  },
  {
    id: 'C033',
    teaser: 'You already know what the right next move is.',
    full: 'You have been deliberating but the information you are waiting for will not change what you already sense is the right call. More data is not going to narrow this gap further.',
    action: 'Make the call today.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'You already know what the right next move is. More data will not change that. Make the call.',
  },
  {
    id: 'C034',
    teaser: 'Deep work today has higher ROI than anything in your meeting schedule.',
    full: 'The calendar may be full but the meetings are not where the high-value work happens right now. The thing that actually moves your position forward requires uninterrupted time to think.',
    action: 'Block two hours for deep work and protect them from interruption.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'Deep work today has higher ROI than anything in your meeting schedule. Block the time and protect it.',
  },
  {
    id: 'C035',
    teaser: 'Someone needs clearer direction from you and has not asked for it.',
    full: 'There is someone who is either proceeding with the wrong assumptions or stalled waiting for guidance they feel uncomfortable requesting. Ambiguity from your side is creating cost on theirs.',
    action: 'Proactively clarify the direction or expectation.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'Someone needs clearer direction from you and has not asked for it. Your ambiguity is costing them.',
  },
  {
    id: 'C036',
    teaser: 'You are performing busyness in a way that is not building anything.',
    full: 'The calendar is full, the emails are moving, the tasks are getting checked. But the score at the end of this week will look the same as it did last week. Busy and productive have diverged.',
    action: 'Name the one thing that would actually move your position. Do that first.',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'You are performing busyness that is not building anything. Busy and productive have diverged this week.',
  },
  {
    id: 'C037',
    teaser: 'An uncomfortable truth from a peer is more useful than you treated it.',
    full: 'Someone said something in passing — a critique, an observation, a comparison — that you deflected. It has been sitting in the background. It was probably more accurate than comfortable.',
    action: 'Sit with it for ten minutes without defending. Extract the useful part.',
    timing: 'You will feel this most before you sleep.',
    shareSnippet: 'An uncomfortable truth from a peer is more useful than you treated it. The accurate part is still there.',
  },
  {
    id: 'C038',
    teaser: 'Your calibration of what is normal is skewed by a bad environment.',
    full: 'If you have spent time in a dysfunctional team or toxic culture, your baseline for what is acceptable effort and treatment may have shifted downward. The cost of that shift is invisible until you leave.',
    action: 'Ask: is this genuinely normal, or have I normalized something I should not have?',
    timing: 'This shows up when you are least distracted.',
    shareSnippet: 'Your calibration of what is normal has been skewed by a bad environment. Check the baseline.',
  },
  {
    id: 'C039',
    teaser: 'A creative block is resolved by doing, not waiting.',
    full: 'You are treating this creative problem as one that will unblock with more time or better conditions. It will not. Creative momentum is generated by output, not by preparatory thinking.',
    action: 'Produce something today. Low quality is fine. Moving is the point.',
    timing: 'Notice this in the first conversation that matters today.',
    shareSnippet: 'A creative block is resolved by doing, not waiting. The momentum starts when you produce something.',
  },
  {
    id: 'C040',
    teaser: 'Someone senior is forming an opinion about your work right now.',
    full: 'There is a window in which a decision-maker or influencer is evaluating something in your orbit. The impression formed in this window has a longer half-life than impressions formed at routine times.',
    action: 'Make sure what is visible today reflects the standard you want associated with your name.',
    timing: 'By tonight, this will be clearer.',
    shareSnippet: 'Someone senior is forming an opinion about your work right now. Make what is visible representative.',
  },
  {
    id: 'C041',
    teaser: 'Talking about the plan is not the same as executing it.',
    full: 'There have been several conversations about this. The plan is agreed upon. What has not happened is the first real action that converts planning into movement. That is the missing piece.',
    action: 'Do one concrete thing today that is execution, not discussion.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'Talking about the plan is not the same as executing it. The first real action is the missing piece.',
  },
  {
    id: 'C042',
    teaser: 'You are holding yourself back to manage other people\'s comfort.',
    full: 'There is a version of you that would move faster, ask for more, or push harder — but you have calibrated yourself down to a level that does not create friction for others. That calibration is costing you.',
    action: 'Push to your actual level today in one area.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'You are holding yourself back to avoid friction. That calibration is costing you something real.',
  },
  {
    id: 'C043',
    teaser: 'The project that feels low-stakes is quietly shaping your reputation.',
    full: 'You have been approaching something as a side item — something that does not really count. But the people it touches have a broader view of your work than you realise.',
    action: 'Give it the attention it deserves, not the attention it feels like it deserves.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'The project that feels low-stakes is quietly shaping your reputation more than you realise.',
  },
  {
    id: 'C044',
    teaser: 'You are closer to a breakthrough than the current difficulty suggests.',
    full: 'The resistance you are encountering right now is not evidence that this is the wrong direction. It is a predictable part of the process. The difficulty is positional, not directional.',
    action: 'Keep going today. Do not change direction based on difficulty alone.',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'You are closer to a breakthrough than the current difficulty suggests. The resistance is positional.',
  },
  {
    id: 'C045',
    teaser: 'A well-timed question will do more than another month of effort.',
    full: 'You are working on something that could be shortcut significantly — not by luck, but by asking the right person the right question. You have been solving in isolation when the answer exists externally.',
    action: 'Identify the thing you are grinding on and ask someone who knows.',
    timing: 'You will feel this most before you sleep.',
    shareSnippet: 'A well-timed question will do more than another month of effort. You have been solving in isolation.',
  },
  {
    id: 'C046',
    teaser: 'You are in the right place but the wrong role.',
    full: 'The environment suits you, the people are right, the mission is aligned — but the specific function you are occupying is constraining output that could be higher in a different position.',
    action: 'Name the role or function where you would operate at peak. Then make one move toward it.',
    timing: 'This shows up when you are least distracted.',
    shareSnippet: 'You are in the right place but the wrong role. The environment is good. The function is the constraint.',
  },
  {
    id: 'C047',
    teaser: 'Speed is costing quality on something that should not be rushed.',
    full: 'You are treating urgency as the primary metric on something where quality matters more than delivery date. The fast version of this will create more work than the careful version.',
    action: 'Slow down on this specific thing. Push the timeline if you need to.',
    timing: 'Notice this in the first conversation that matters today.',
    shareSnippet: 'Speed is costing quality on something that should not be rushed. The fast version will create more work.',
  },
  {
    id: 'C048',
    teaser: 'Recognition you expected has not arrived. It still might.',
    full: 'You did the work. The acknowledgement has been delayed — possibly by competing priorities, possibly by oversight. Do not perform indifference. The gap between the work and the acknowledgement is normal.',
    action: 'Do not diminish the work retroactively. It was good. Make sure the right person knows.',
    timing: 'By tonight, this will be clearer.',
    shareSnippet: 'Recognition you expected has not arrived. Do not diminish the work. The acknowledgement is delayed.',
  },
  {
    id: 'C049',
    teaser: 'The problem is not as complex as the conversation around it.',
    full: 'There has been a lot of discussion about this. The discussion has developed a life that is longer than the actual problem. Someone needs to simplify the frame so action becomes possible.',
    action: 'State the core problem in one sentence. Build from that.',
    timing: 'Pay attention to this before the day gets complicated.',
    shareSnippet: 'The problem is not as complex as the conversation around it. Someone needs to simplify the frame.',
  },
  {
    id: 'C050',
    teaser: 'An energy shift in the next few hours will clarify something that has been murky.',
    full: 'There is a decision or situation that has felt ambiguous. The fog is close to lifting — not from outside information, but from your own internal processing finishing. Do not rush the decision before the clarity arrives.',
    action: 'Wait for the clarity. When it comes, act immediately.',
    timing: 'This tends to surface by evening.',
    shareSnippet: 'An energy shift in the next few hours will clarify something that has been murky. Do not rush before then.',
  },
  {
    id: 'C051',
    teaser: 'What you are calling perfectionism is also called avoidance.',
    full: 'The standard you are holding this to is higher than necessary and is functioning as a reason not to ship, submit, or show up. At some point, the standard becomes a wall, not a quality gate.',
    action: 'Submit the thing that is ninety percent done. Today.',
    timing: 'The signal is strongest in unguarded moments.',
    shareSnippet: 'What you are calling perfectionism is also called avoidance. The standard is now a wall, not a gate.',
  },
  {
    id: 'C052',
    teaser: 'A learning investment today will pay off faster than any execution effort.',
    full: 'There is a skill, tool, or approach that you have been meaning to understand properly. The time to learn it feels like it competes with the time to do the work. It does not. It is the work.',
    action: 'Spend one focused hour learning the thing you have been deferring.',
    timing: 'Watch how this plays out after noon.',
    shareSnippet: 'A learning investment today will pay off faster than any execution effort. The learning is the work.',
  },
];
