// Love predictions – 52 entries
// Tone: sharp, grounded, slightly mysterious. Not astrology-cringe.
// Each has: teaser (hook), full (depth), action (concrete step).

export const love = [
  {
    id: 'L001',
    teaser: 'Someone is reading more into your words than you intended.',
    full: 'Small things you say carry more weight than usual right now. A tone, a word choice, a silence — someone close is parsing all of it carefully. You may not realise the signal you are actually sending.',
    action: 'Before you reply to anyone important today, pause and ask: is this what I actually mean?',
  },
  {
    id: 'L002',
    teaser: 'You love more quietly than you let on.',
    full: 'There is a gap between how much you feel and how much you show. This is not coldness — it is protection. But the people closest to you may be reading it as distance, not depth.',
    action: 'Say one small thing today that leaves no room for misreading.',
  },
  {
    id: 'L003',
    teaser: 'An old conversation is still unfinished.',
    full: 'Something was left in ambiguity — either on purpose or by accident. Both of you know it. The longer it sits, the more meaning it accumulates, and not all of it is accurate.',
    action: 'Decide today: resolve it, or consciously let it go. Either is fine. Neither is not.',
  },
  {
    id: 'L004',
    teaser: 'You are more drawn to someone than you are admitting.',
    full: 'There is a pull you have been rationalising away. Logic is useful, but sometimes it is being applied to avoid discomfort rather than to arrive at truth.',
    action: 'Notice what you are feeling without acting on it. You do not have to move — just stop pretending it is not there.',
  },
  {
    id: 'L005',
    teaser: 'Someone remembers something you said weeks ago. They have not forgotten.',
    full: 'You spoke casually. They heard something more significant. This can go in two directions — a pleasant surprise or a quiet awkwardness. Either way, you should know.',
    action: 'Check in with someone you have not spoken to recently.',
  },
  {
    id: 'L006',
    teaser: 'You are both waiting for the other person to move first.',
    full: 'A standoff has developed — not dramatic, but real. Both sides want movement but neither wants to initiate. Someone has to go first, and neither of you is making it easy.',
    action: 'Be the one who moves first. It takes less courage than the waiting does.',
  },
  {
    id: 'L007',
    teaser: 'Their distance today is about them, not about you.',
    full: 'Their attention is elsewhere — not pulled away by someone else, but by something internal they have not fully processed. Reading it as a shift toward you would be the wrong interpretation.',
    action: 'Give a little more space than feels comfortable. See what it returns.',
  },
  {
    id: 'L008',
    teaser: 'A small gesture today will land differently than you expect.',
    full: 'Context is shifting. Something you would normally do without thinking — a message, a question, a compliment — will carry unusual weight right now. The timing matters.',
    action: 'Think before you act today. Be more deliberate than usual.',
  },
  {
    id: 'L009',
    teaser: 'You have been performing okayness for too long.',
    full: 'There is a version of you that keeps things smooth even when they are not. The effort this takes is draining a resource you will need for something real.',
    action: 'Tell one person how you are actually doing — not the edited version.',
  },
  {
    id: 'L010',
    teaser: 'The attraction that feels new is actually a pattern you recognise.',
    full: 'This feeling has a shape you have felt before. Recognising that shape is not cynicism — it is information. It tells you what part of you this is speaking to.',
    action: 'Before going further, ask yourself what you want this to become.',
  },
  {
    id: 'L011',
    teaser: 'A relationship you have stopped tending will ask for something today.',
    full: 'The dynamic has been on autopilot. That works until it does not. Something is about to surface that will require actual attention instead of assumed continuity.',
    action: 'Reach out before they have to.',
  },
  {
    id: 'L012',
    teaser: 'You give differently than you like to receive.',
    full: 'What you offer — time, practicality, presence — does not always match what you actually want back. This mismatch is invisible to you but visible to people paying attention.',
    action: 'Name what you actually want today. Even just to yourself.',
  },
  {
    id: 'L013',
    teaser: 'Someone is hoping you remember something you might have forgotten.',
    full: 'A small detail — a plan, a promise, a date — is sitting in someone\'s memory waiting to be acknowledged. They have not reminded you. You should check.',
    action: 'Think back across the last two weeks of conversations.',
  },
  {
    id: 'L014',
    teaser: 'Your sharpness today can cut in ways you will not see until later.',
    full: 'You are operating with more edge than usual — fast, impatient, a little compressed. In most situations this works. In one conversation today, it will not.',
    action: 'In any emotionally loaded exchange, drop your pace by half.',
  },
  {
    id: 'L015',
    teaser: 'The thing you want to say keeps getting postponed.',
    full: 'There is something honest and important that you keep finding reasons to delay. The reasons feel logical. They may actually be fear dressed as practicality.',
    action: 'Set a deadline. This week, not next.',
  },
  {
    id: 'L016',
    teaser: 'They are pulling back not to withdraw — to recalibrate.',
    full: 'You may read the distance as rejection. It is not. They are working something out internally. What they need right now is steady presence, not pursuit.',
    action: 'Stay available without making your availability feel like pressure.',
  },
  {
    id: 'L017',
    teaser: 'You are more forgiving of others than you are of yourself.',
    full: 'You have extended grace to people who have done more than this person has done. The standard you hold yourself to is tighter than any standard you hold anyone else to.',
    action: 'Offer yourself the same interpretation you would give a close friend.',
  },
  {
    id: 'L018',
    teaser: 'Physical proximity is making something feel more urgent than it is.',
    full: 'When you are near them, the feeling intensifies. When you are apart, it settles. That pattern is telling you something about what is situational versus what is real.',
    action: 'Test the feeling from a distance before acting on it.',
  },
  {
    id: 'L019',
    teaser: 'An apology is due but traveling slowly.',
    full: 'Someone knows they owe you something. They are circling it, uncomfortable, not quite finding the moment. It will arrive eventually. Do not pull it.',
    action: 'Make space for it without performing expectation.',
  },
  {
    id: 'L020',
    teaser: 'Someone is thinking about you without showing up in your day.',
    full: 'There is someone whose thoughts keep returning to you without their presence being visible in your life right now. This kind of quiet attention always surfaces eventually.',
    action: 'Notice who comes to mind today without a clear reason.',
  },
  {
    id: 'L021',
    teaser: 'Compatibility and chemistry are answering different questions.',
    full: 'What you feel right now is real — but it is answering a different question than the one you think it is. Chemistry creates interest. Compatibility is what makes something last.',
    action: 'Think about the last three weeks, not the last three hours.',
  },
  {
    id: 'L022',
    teaser: 'A small neglect has quietly compounded into distance.',
    full: 'It started as a busy week. Then another. Then it became the default. The gap between you and someone close is wider than either of you has acknowledged out loud.',
    action: 'Schedule something — even brief, even low-key — and do not let it slide.',
  },
  {
    id: 'L023',
    teaser: 'You are looking for certainty in something that is still forming.',
    full: 'Wanting to know the outcome before the process completes is adding pressure to something that needs room to develop. You are trying to skip the ambiguous middle.',
    action: 'Let this develop at its own pace for a few more days.',
  },
  {
    id: 'L024',
    teaser: 'The conversation you are dreading would clear the air fastest.',
    full: 'There is a specific exchange you have been avoiding because it could go either way. The avoidance is not neutral — it is making the air heavier for both of you.',
    action: 'Start it. Even imperfectly. Especially if you are not ready.',
  },
  {
    id: 'L025',
    teaser: 'Someone is drawn to the version of you that does not try as hard.',
    full: 'When you relax your effort — when you are simply yourself without the performance layer — something in the dynamic improves noticeably. You have probably noticed this.',
    action: 'Show up today with less presentation, more presence.',
  },
  {
    id: 'L026',
    teaser: 'The expectation you are carrying was never agreed to.',
    full: 'You expect something specific from someone — regular attention, reciprocal energy, a particular kind of response. They do not know this is expected. And yet you are measuring them against it.',
    action: 'Name the expectation clearly. Say it once.',
  },
  {
    id: 'L027',
    teaser: 'Timing is doing more work here than you are giving it credit for.',
    full: 'The feeling is right; the window might not be. Sometimes the difference between a good idea and a bad one is simply when it arrives. This is one of those situations.',
    action: 'Wait three more days before any major move.',
  },
  {
    id: 'L028',
    teaser: 'What you call independence looks like unavailability from the outside.',
    full: 'You have made yourself harder to reach — not maliciously, but as a habit. Most people have adapted. One person has not, and it is costing something neither of you has named.',
    action: 'Be intentionally accessible to one specific person today.',
  },
  {
    id: 'L029',
    teaser: 'You are holding a version of someone from a year ago.',
    full: 'The reference point you are using is outdated. They have changed — possibly in ways you would like, possibly not. Your response is lagging behind the actual person in front of you.',
    action: 'Pay attention to who they actually are this week, not who they were.',
  },
  {
    id: 'L030',
    teaser: 'Today favors honesty over strategy.',
    full: 'There is a conversation where you have been managing your words carefully, controlling outcomes, staying calculated. Today that approach will underperform. Directness will land better.',
    action: 'Say the thing directly. One sentence, no softening.',
  },
  {
    id: 'L031',
    teaser: 'Someone is more interested than they are letting on.',
    full: 'They are containing it — staying cooler than they feel, not wanting to seem eager. Watch the small tells, not what they say explicitly. The signal is there.',
    action: 'Meet their subtlety with a small, clear signal of your own.',
  },
  {
    id: 'L032',
    teaser: 'You have been the stronger person in this dynamic for too long.',
    full: 'Strength is good until it becomes load-bearing for both of you. At some point the imbalance costs you something — and you have been paying it quietly without acknowledgement.',
    action: 'Let them carry something this week. Let yourself be carried.',
  },
  {
    id: 'L033',
    teaser: 'A past pattern is shaping how you read the present.',
    full: 'You are applying an old interpretation to a new situation. The current person is not behaving the same way the previous one did — you are filling gaps with memory from a different story.',
    action: 'Ask before you assume.',
  },
  {
    id: 'L034',
    teaser: 'Closeness is producing some friction today.',
    full: 'The better you know someone, the more clearly you see the parts that do not fit perfectly. Today you are seeing those parts more than the rest. That is proximity, not incompatibility.',
    action: 'Zoom out. What does the whole picture look like?',
  },
  {
    id: 'L035',
    teaser: 'You are more attached than your behavior is suggesting.',
    full: 'Internally, the investment is high. Externally, you are projecting neutrality. This mismatch is confusing someone who is trying to read where you actually stand.',
    action: 'Show a little more of what is actually there.',
  },
  {
    id: 'L036',
    teaser: 'The silence between you carries a specific weight today.',
    full: 'It is not neutral silence. It is the kind that holds an unspoken thing. Both of you know it. The longer it holds, the larger the unspoken thing becomes.',
    action: 'Break it. Anything honest will do.',
  },
  {
    id: 'L037',
    teaser: 'Someone is comparing you to who you used to be.',
    full: 'They have a reference point — and they are noticing the delta. Whether the change is good or not from their perspective depends on what shifted. Best to ask directly rather than guess.',
    action: 'Find out what they are seeing that you might be missing.',
  },
  {
    id: 'L038',
    teaser: 'Unreciprocated effort is building into something quiet and corrosive.',
    full: 'You have been doing more. It has not been acknowledged. You have not said anything. The gap between what you give and what returns is growing into a ledger you never wanted to keep.',
    action: 'Either ask for reciprocation or consciously stop the accounting.',
  },
  {
    id: 'L039',
    teaser: 'A good conversation today could reset something that has felt heavy.',
    full: 'Whatever tension has been ambient between you — even mild, even unnamed — a real conversation right now could dissolve it faster than you expect. The timing is actually right.',
    action: 'Start it without an agenda. Let it find its own direction.',
  },
  {
    id: 'L040',
    teaser: 'You are waiting for them to say it first.',
    full: 'It is a gamble. They might. But if they do not, the gap widens and you are further from what you want. The first-mover advantage in this situation is real and it belongs to whoever takes it.',
    action: 'Say it plainly.',
  },
  {
    id: 'L041',
    teaser: 'A small shared thing carries more meaning today than it usually would.',
    full: 'An inside reference, a repeated ritual, something ordinary between you — one of these will feel unexpectedly significant. Let it. Do not analyse it away.',
    action: 'Be fully present in whatever small thing you share today.',
  },
  {
    id: 'L042',
    teaser: 'Someone is asking for less than they actually need.',
    full: 'They know you are busy, or they do not want to impose, or they have learned to minimize their requests around you. Watch for what is not being asked. That is often the real thing.',
    action: 'Give a little more than was asked.',
  },
  {
    id: 'L043',
    teaser: 'A comparison is being made, and you are not the one making it.',
    full: 'Someone in your orbit is measuring you against someone else — consciously or not. This is not necessarily threatening. But it is happening, and you are the variable being evaluated.',
    action: 'Be distinctly yourself today. The authentic version, not the performance.',
  },
  {
    id: 'L044',
    teaser: 'You are hesitating on something that is already decided.',
    full: 'The decision is made internally — you know it. The hesitation now is about the cost of acting on what you already know to be true. You are not undecided. You are just not ready to move.',
    action: 'Take one step in the direction you already know.',
  },
  {
    id: 'L045',
    teaser: 'Their low energy today has nothing to do with you.',
    full: 'They are quieter, less present, a little pulled inward. The instinct is to read this as a shift toward you. It is not. They are carrying something unrelated that has not surfaced yet.',
    action: 'Ask how they are doing without fishing for reassurance.',
  },
  {
    id: 'L046',
    teaser: 'You are giving time without giving presence.',
    full: 'You are showing up — but that phrase is doing a lot of work. The hours are there but the attention is not fully there. They can tell the difference, even if they cannot articulate it.',
    action: 'Give twenty minutes of complete, undivided attention to one person today.',
  },
  {
    id: 'L047',
    teaser: 'An honest conversation is cheaper than a misunderstanding.',
    full: 'Whatever you are trying to avoid by staying vague costs more than saying it clearly would. The discomfort of the direct path is smaller than you are imagining. The cost of the indirect path is bigger than you are tracking.',
    action: 'Have the conversation you have been engineering your way around.',
  },
  {
    id: 'L048',
    teaser: 'You are more ready than you think you are.',
    full: 'There is a step you have been delaying because the conditions do not feel ideal. They will not be ideal. But you are more prepared for this than you are giving yourself credit for.',
    action: 'Move today.',
  },
  {
    id: 'L049',
    teaser: 'Something you dismissed too quickly deserves another look.',
    full: 'A feeling, an observation, a person — you moved past it faster than it warranted. It is still in your peripheral vision, waiting to be seen properly instead of managed efficiently.',
    action: 'Return to it with fresh attention.',
  },
  {
    id: 'L050',
    teaser: 'The right person for today\'s version of you is not who you assumed.',
    full: 'What you need has shifted. The requirements of today\'s version of you are different from what they were two years ago. Take stock of who actually fits that version, not who used to.',
    action: 'Spend less time recreating the past. What would good look like now?',
  },
  {
    id: 'L051',
    teaser: 'Vulnerability feels like weakness right now. It is not.',
    full: 'There is something real you are protecting behind a composed exterior. The wall is functional. But it is also creating a ceiling on what this connection can become.',
    action: 'Let one small true thing be visible today.',
  },
  {
    id: 'L052',
    teaser: 'The energy between you has changed recently, and both of you feel it.',
    full: 'Something shifted — you may not be able to point to the exact moment, but the texture of the dynamic is different. Ignoring it takes effort. Naming it takes less.',
    action: 'Acknowledge the shift, even briefly. It clears more than you expect.',
  },
];
