// Money predictions – 52 entries
// Tone: grounded, sharp, behavioral finance framing.

export const money = [
  {
    id: 'M001',
    teaser: 'An impulse you have been managing for a week is about to win.',
    full: 'There is a purchase or financial decision you have been circling — rationalising it, justifying the cost, finding reasons it makes sense. The rationalisations are not analysis. They are post-hoc justification.',
    action: 'Wait 48 hours from any non-essential purchase above ₹2000 you are currently considering.',
  },
  {
    id: 'M002',
    teaser: 'A small recurring expense is larger than you think it is across a year.',
    full: 'There is something you are paying regularly that barely registers per transaction. Multiplied out, it is significantly more than you treat it as. The invisibility of recurring costs is not an accident of life — it is how they work.',
    action: 'Audit one recurring payment you have not reviewed in six months.',
  },
  {
    id: 'M003',
    teaser: 'Money is entering an easier period than the last one.',
    full: 'The pressure of the last cycle — the tightness, the calculating, the deferring — is loosening. This is a reasonable time to rebuild what was drawn down, rather than expand spending proportionally.',
    action: 'Redirect any new breathing room into something that builds, not something that spends.',
  },
  {
    id: 'M004',
    teaser: 'An unexpected expense is coming. You do not yet know the amount.',
    full: 'Something will cost money in the next two to three weeks that you are not accounting for in your current mental model. This is not a catastrophe — but it is not a good time to tighten cash.',
    action: 'Keep more buffer than usual for the next three weeks.',
  },
  {
    id: 'M005',
    teaser: 'Someone in your life is managing money better than they appear to be.',
    full: 'You have a reference point for someone\'s financial situation that is based on old information or visible signals. The actual picture may be significantly different. Do not benchmark to a model that may not be accurate.',
    action: 'Update your assumptions about other people\'s situations before using them as comparison.',
  },
  {
    id: 'M006',
    teaser: 'You are paying the convenience tax on something you have not optimised.',
    full: 'There is a financial arrangement — a service, a subscription, a provider — that you are sticking with out of inertia rather than because it is the best available option. Switching feels like effort. It would take less time than you think.',
    action: 'Identify one arrangement where you could get better value with less than thirty minutes of effort.',
  },
  {
    id: 'M007',
    teaser: 'Delayed gratification is working in your favor right now without you noticing.',
    full: 'Something you set in motion months ago — a saving habit, a deferred purchase, a disciplined choice — is quietly compounding in your favor. The payoff is not dramatic but it is real.',
    action: 'Acknowledge the progress that does not feel like progress. Then keep going.',
  },
  {
    id: 'M008',
    teaser: 'You are spending on reasons, not on value.',
    full: 'A recent or upcoming expense is justified by a story — a deserving, a celebration, a comparison to someone else\'s spending. The story is real but it is not the same as the expense being the best use of the money.',
    action: 'Name what you are actually buying. Then decide if the spend matches what you named.',
  },
  {
    id: 'M009',
    teaser: 'A financial opportunity has a shorter window than you are treating it as.',
    full: 'There is a decision — an investment, a deal, a negotiation — where you have been operating as if you can revisit it at your leisure. The window is narrower. Delay has a cost here.',
    action: 'Make the decision in the next 24 hours, or decide definitively that you are not making it.',
  },
  {
    id: 'M010',
    teaser: 'Your income is growing slower than your expenses are.',
    full: 'The gap between earning and spending has been narrowing — not because of one dramatic shift but because of gradual lifestyle expansion. The trend is gentle enough to miss, which is exactly what makes it dangerous.',
    action: 'Compare your monthly spend this month to six months ago. The number will be informative.',
  },
  {
    id: 'M011',
    teaser: 'You are avoiding a money conversation that you need to have.',
    full: 'There is someone — a partner, a family member, a business associate — with whom you have an unresolved financial matter. The avoidance is not free. It is accumulating interest in the form of resentment or risk.',
    action: 'Initiate the conversation. Keep it factual and specific.',
  },
  {
    id: 'M012',
    teaser: 'The comparison is making you spend on things that do not matter to you.',
    full: 'You are buying things that make sense relative to what you see around you — not things that actually reflect your own priorities. Social spending is not inherently wrong but it is not the same as intentional spending.',
    action: 'Identify one recent expense that was driven more by comparison than by genuine want.',
  },
  {
    id: 'M013',
    teaser: 'A cheap decision now may become an expensive one later.',
    full: 'There is something you are purchasing or hiring at the lower end of available quality. The upfront saving is real. The downstream cost — of time, replacement, or redoing — may exceed it.',
    action: 'For one current decision, calculate whether cheap now is actually cheap total.',
  },
  {
    id: 'M014',
    teaser: 'You have assets that are idle when they could be working.',
    full: 'There is capability, time, intellectual output, or a physical resource that is sitting underutilized and could generate income or value if you deployed it differently.',
    action: 'Name one idle asset. Think for ten minutes about how it could produce.',
  },
  {
    id: 'M015',
    teaser: 'Scarcity thinking is making you avoid a decision that has real upside.',
    full: 'There is an investment, spend, or risk you are avoiding not because the numbers do not work, but because the default mode right now is protective. Fear of losing what you have is keeping you from gaining.',
    action: 'Run the numbers without the fear assumption. What does the rational analysis say?',
  },
  {
    id: 'M016',
    teaser: 'Your financial stress has a specific source that you are treating as general.',
    full: 'The anxiety about money right now is not diffuse — it is coming from one specific thing: a specific number, a specific obligation, a specific timeline. Treating it as general keeps it large and formless.',
    action: 'Name the one specific source. Then make a plan for just that one thing.',
  },
  {
    id: 'M017',
    teaser: 'A disciplined moment now prevents a desperate one in two months.',
    full: 'The decision in front of you feels neutral now — it would not significantly change anything today. But the cumulative effect of this kind of decision over the next eight weeks compounds into a real difference.',
    action: 'Make the disciplined choice today, even without the pressure to.',
  },
  {
    id: 'M018',
    teaser: 'Someone owes you money and you have been too polite to mention it.',
    full: 'There is an amount — maybe small — that has been sitting without acknowledgement. The longer it sits, the more awkward the retrieval becomes, and the less likely it is to happen without friction.',
    action: 'Bring it up today. Casually, specifically, and soon.',
  },
  {
    id: 'M019',
    teaser: 'The financial plan you made has been overtaken by events you have not updated for.',
    full: 'Circumstances have changed since you last set your financial intentions — income shifted, priorities changed, expenses moved. The original plan may now be pointing at a target that no longer exists.',
    action: 'Spend twenty minutes updating your actual numbers to reflect current reality.',
  },
  {
    id: 'M020',
    teaser: 'Money and self-worth are currently tangled in a way that is distorting both.',
    full: 'What you earn, what you spend, what you save — all of it is carrying emotional weight that is not really about money. The decisions you are making are sometimes about the feeling, not the finances.',
    action: 'Make one financial decision today that is purely about the numbers, not the feeling.',
  },
  {
    id: 'M021',
    teaser: 'The highest-return investment you can make currently is in a specific skill.',
    full: 'A course, a certification, a tool — there is a learning investment that would increase your earning capacity more than any passive investment available to you at your current wealth level.',
    action: 'Identify what skill would have the most direct impact on your financial position. Then invest in learning it.',
  },
  {
    id: 'M022',
    teaser: 'An upcoming large expense is manageable if you prepare now.',
    full: 'There is something you know will cost significantly — a tax obligation, a purchase, an event — that is visible on the horizon. Preparing a little in advance removes a lot of the pressure when it lands.',
    action: 'Set aside one specific amount today toward the known future expense.',
  },
  {
    id: 'M023',
    teaser: 'Your relationship with risk is currently calibrated too conservatively.',
    full: 'At your current position in life, more risk-taking in finances would be rational. The floor risks are lower than you are treating them. The upside of appropriately calibrated risk-taking is larger than avoidance.',
    action: 'Name one financial move you have been avoiding due to fear of loss. Evaluate it at its actual risk level.',
  },
  {
    id: 'M024',
    teaser: 'A discount or benefit you are entitled to is going unclaimed.',
    full: 'There is a saving — a negotiation, a benefit, a reimbursement — available to you right now that you have not pursued. The money is not missing. It is just uncollected.',
    action: 'Identify one entitled benefit or saving and claim it today.',
  },
  {
    id: 'M025',
    teaser: 'Your most productive earning channel is being underutilized.',
    full: 'You have multiple ways your financial value expresses itself. One of them has a significantly higher return per unit of input than the others. You have been distributing effort evenly when you should be concentrating it.',
    action: 'Identify your highest ROI activity and allocate more time to it this week.',
  },
  {
    id: 'M026',
    teaser: 'Generosity is not the problem. Resentful generosity is.',
    full: 'You give to people in your life — financially, materially. When it comes from choice, it is good. When it comes from obligation or social pressure and you resent it afterward, both the relationship and the money are being spent badly.',
    action: 'Name one financial give that you resent. Either stop it or consciously recommit to it.',
  },
  {
    id: 'M027',
    teaser: 'The stress about money is louder than the actual problem right now.',
    full: 'Your anxiety about finances is running ahead of your actual financial position. The worry is not inaccurate but it is amplified. The numbers are better than the feeling.',
    action: 'Write down your actual numbers. Then see if the worry matches the reality.',
  },
  {
    id: 'M028',
    teaser: 'An investment that seemed idle is actually performing.',
    full: 'Something you put in motion — money, time, a relationship, a commitment — that has felt dormant or slow is actually developing in ways that are not yet visible in the obvious metrics.',
    action: 'Check the actual numbers on something you last looked at two months ago.',
  },
  {
    id: 'M029',
    teaser: 'You are earning at a level below what you are worth to the right client or employer.',
    full: 'The gap between what you are paid and what you could be paid for the same work in a different context is real and significant. The constraint is not the market — it is the specific arrangement you are currently in.',
    action: 'Research what the same skills or output earns in three other contexts.',
  },
  {
    id: 'M030',
    teaser: 'The budget you made was too tight to survive reality.',
    full: 'Budgets that do not account for the friction of real life — unexpected costs, mood-driven decisions, social pressures — do not hold. They just produce guilt. A realistic budget is better than a perfect one.',
    action: 'Add a 15% buffer to whatever your current spending plan is.',
  },
  {
    id: 'M031',
    teaser: 'Today\'s buying impulse is tomorrow\'s low-grade regret.',
    full: 'There is a purchase in your environment right now that is triggering a desire that feels genuine. The desire is real. But the satisfaction from the specific purchase will be much shorter than the feeling of wanting suggests.',
    action: 'Wait 24 hours. If you still want it genuinely, buy it consciously. If not, you have your answer.',
  },
  {
    id: 'M032',
    teaser: 'Your earning potential is growing but your confidence in it is not.',
    full: 'You are better at what you do than you were a year ago. The market would pay more for the current version of your skills. But you are still pricing yourself from the old version of your confidence.',
    action: 'In your next relevant negotiation, ask for more than you currently plan to.',
  },
  {
    id: 'M033',
    teaser: 'A cash flow problem is masking a profitability problem.',
    full: 'When money feels tight, the instinct is to fix the timing of cash. But sometimes the real issue is that the underlying activity is not generating enough margin. Fix the right thing.',
    action: 'Look at whether the tightness is about timing or about fundamentals.',
  },
  {
    id: 'M034',
    teaser: 'The financial safety net you think you have is thinner than the feeling suggests.',
    full: 'There is a comfort level around your emergency fund or financial buffer that does not fully match the actual numbers. The feeling of security and the reality of security have diverged slightly.',
    action: 'Check the actual number today. Know precisely what is there.',
  },
  {
    id: 'M035',
    teaser: 'Spending on an experience will return more than spending on an object.',
    full: 'If there is a meaningful purchase in your near term, the research consistently shows that experiences — travel, learning, time with people who matter — generate longer satisfaction than things.',
    action: 'If you are going to spend on yourself this month, spend it on an experience.',
  },
  {
    id: 'M036',
    teaser: 'You have been working hard. Your financial position is not reflecting it yet.',
    full: 'There is lag between input and output in financial life, particularly early in careers or during transition periods. The work is accumulating value that has not yet converted to numbers. This is temporary.',
    action: 'Focus on the leading indicators — skills, relationships, deliverables — not just the lagging ones.',
  },
  {
    id: 'M037',
    teaser: 'A financial shortcut you are considering has hidden costs.',
    full: 'There is an option that looks like it saves money or effort but requires you to cut a corner somewhere. The corner seems unimportant. It may not be.',
    action: 'Name the thing being cut. Then evaluate whether the saving is worth the specific risk.',
  },
  {
    id: 'M038',
    teaser: 'The income you are expecting may be delayed or reduced.',
    full: 'Something in your income pipeline may not land exactly as planned — a payment delayed, a decision postponed, an amount revised. This is not a permanent problem but it is a cash flow reality to plan around.',
    action: 'Check two weeks out. Do your inflows actually match your expenses in that window?',
  },
  {
    id: 'M039',
    teaser: 'The best financial move you can make today costs nothing.',
    full: 'It is a decision: to stop, to exit, to say no, to stop paying for something that is not serving you. The most valuable financial decisions are often subtractive, not additive.',
    action: 'Name one financial commitment you should cut. Then cut it.',
  },
  {
    id: 'M040',
    teaser: 'A financial pattern from your family is running in the background.',
    full: 'The way your family of origin handled money — the anxiety, the generosity, the avoidance, the ambition — is in your programming. It is not your fault. But it is your job to examine it.',
    action: 'Identify one money behavior you have that came from watching others in your family.',
  },
  {
    id: 'M041',
    teaser: 'You are overanalyzing something that should just be decided.',
    full: 'The information is sufficient. More analysis is not going to produce a qualitatively better decision here. You are using research as a way to delay a commitment that has some discomfort in it.',
    action: 'Make the financial decision today with what you know.',
  },
  {
    id: 'M042',
    teaser: 'Celebrating progress is not the same as spending on it.',
    full: 'There is a tendency to mark milestones with purchases. The impulse is understandable. But the celebration and the expense do not need to be the same event.',
    action: 'Celebrate the milestone without buying something to mark it.',
  },
  {
    id: 'M043',
    teaser: 'A financial goal without a number is just a wish.',
    full: 'You have financial intentions — to save more, to invest, to reduce debt. But the intentions lack specific targets and timelines. Without those, there is no mechanism for accountability or progress.',
    action: 'Pick one financial goal. Assign a specific number and a specific date. Write it down.',
  },
  {
    id: 'M044',
    teaser: 'The income from a side effort is more significant than its small feeling suggests.',
    full: 'There is supplementary income you have been treating as bonus rather than building. Even moderate supplementary income, compounded or invested consistently, changes the long-term picture materially.',
    action: 'Treat the supplementary income as a building block, not spending money.',
  },
  {
    id: 'M045',
    teaser: 'Something you thought was expensive is actually good value.',
    full: 'There is a cost — a service, a tool, a professional — that you have been resisting as too high. The price versus the actual value delivered may be better than you have given it credit for.',
    action: 'Re-evaluate one expense you dismissed recently. Calculate what it is actually worth per use or per hour.',
  },
  {
    id: 'M046',
    teaser: 'Your financial anxiety is costing you actual money.',
    full: 'Stress about money produces short-term decisions — panic-selling, over-caution, avoidance of planning — that have real financial consequences. The anxiety is not protective. It is expensive.',
    action: 'Name one decision you have made recently from financial fear. Would you make the same call from a calm position?',
  },
  {
    id: 'M047',
    teaser: 'A negotiation you have been avoiding is worth the discomfort.',
    full: 'There is a financial arrangement — a salary, a contract, a price — where you are accepting the first number when asking would likely produce a better one. The discomfort of asking is priced into the answer you are not getting.',
    action: 'Ask for better terms on one active arrangement this week.',
  },
  {
    id: 'M048',
    teaser: 'The frugality you are applying in some areas is not coherent with the spending in others.',
    full: 'You are disciplined about some categories and unexamined in others. The careful tracking of small things while ignoring large variable costs is not a financial strategy — it is selective attention.',
    action: 'Identify your largest single spending category. Is the level of scrutiny there proportionate to its size?',
  },
  {
    id: 'M049',
    teaser: 'Now is a reasonable time to ask for more.',
    full: 'Whatever the context — a raise, a rate increase, a renegotiation — the conditions are not worse than they were and possibly better. The timing feels uncertain because timing always feels uncertain. Ask anyway.',
    action: 'Initiate a conversation about money with someone who owes you something better.',
  },
  {
    id: 'M050',
    teaser: 'Your current financial position is a snapshot, not a sentence.',
    full: 'What the numbers show today is not fixed. It is the result of earlier decisions, some of which were not optimal. The next set of decisions is being made now and they will change the snapshot.',
    action: 'Make one decision today that moves the snapshot in the direction you want it to go.',
  },
  {
    id: 'M051',
    teaser: 'You are paying for access you are not using.',
    full: 'There is a subscription, membership, or paid account that was worth it at the time and is now costing money for access you rarely use. The switching cost feels high. It is lower than the accumulating spend.',
    action: 'Cancel or pause one paid service you have not used this month.',
  },
  {
    id: 'M052',
    teaser: 'The amount you spend on stress relief is worth auditing.',
    full: 'Food delivery, impulse shopping, paid entertainment that you scroll through — a portion of your spending is functioning as stress management. Understanding the pattern does not require eliminating it. But it should be intentional.',
    action: 'Track the spend triggered by stress for the next seven days. No judgement. Just data.',
  },
];
