// Money predictions – 52 entries
// Tone: grounded, sharp, behavioral finance framing.
// Each has: teaser (hook), full (depth), action (concrete step), timing (hint), shareSnippet (share text).

export const money = [
 {
 id: 'M001',
 teaser: 'A small money decision today will feel bigger than it is.',
 full: 'The decision is manageable but it\'ll arrive with more weight than it deserves. A price, a fee, a routine transaction will trigger more deliberation than the actual number warrants. That\'s a signal about the category, not the amount.',
 action: 'Make the decision at the size it actually is, not the size the feeling suggests.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A small money decision today will feel bigger than it is. The feeling is about the category, not the amount.',
 },
 {
 id: 'M002',
 teaser: 'You\'ll be tempted to justify a purchase you already know isn\'t right.',
 full: 'The rationalization will be convincing — there are good arguments for it, the timing feels reasonable, you will find a use for it. But you already know the answer. The arguments are post-hoc comfort, not analysis.',
 action: 'If you already know the answer, stop finding reasons to reverse it.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'You\'ll be tempted to justify a purchase you already know isn\'t right. The rationalization is not analysis.',
 },
 {
 id: 'M003',
 teaser: 'Something expected around money today will cost more than you planned.',
 full: 'A bill, a service, a purchase you\'d mentally priced will come in higher than anticipated. The surprise is useful data about your mental cost model. Don\'t just pay it — note the gap.',
 action: 'Note the discrepancy and update your estimates for similar items.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Something expected around money today will cost more than you planned. Note the gap in your mental model.',
 },
 {
 id: 'M004',
 teaser: 'An unexpected payment request will show up today.',
 full: 'Something will arrive — a bill, a request, a fee — that you weren\'t tracking or had moved to the background. The amount will be manageable but the timing will feel off.',
 action: 'Deal with it today if it\'s legitimate. Don\'t let it sit.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'An unexpected payment request will show up today. Deal with the legitimate ones immediately.',
 },
 {
 id: 'M005',
 teaser: 'A money conversation you\'ve been avoiding will push its way into today.',
 full: 'Something you\'ve been deferring — a specific conversation about finances with someone — will surface. Either an opportunity arrives, or a situation forces it, or the other person initiates. It\'ll be harder to avoid than before.',
 action: 'If it surfaces today, go through it rather than rescheduling.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'A money conversation you\'ve been avoiding will push its way into today. Go through it rather than past it.',
 },
 {
 id: 'M006',
 teaser: 'A financial decision that\'s been sitting will need an answer today.',
 full: 'You\'ve been living with ambiguity on something that actually needs to resolve. A payment, a choice, a commitment — the indecision has been its own form of choice. Today the situation asks for a deliberate answer.',
 action: 'Give it one. Even an imperfect decision is better than continued ambiguity here.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'A financial decision that\'s been sitting will need an answer today. An imperfect decision beats continued ambiguity.',
 },
 {
 id: 'M007',
 teaser: 'A number will surprise you today — in either direction.',
 full: 'An account balance, a price, a bill — some number will land differently from what you expected. If it\'s a pleasant surprise, use the feeling to inform better tracking. If it\'s an unpleasant one, use it the same way.',
 action: 'Don\'t just react to the number. Ask what it reveals about where your mental model was off.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'A number will surprise you today. What matters is what it reveals about your assumptions.',
 },
 {
 id: 'M008',
 teaser: 'A purchase you\'ve been holding off will suddenly feel urgent today. It isn\'t.',
 full: 'The urgency will feel real — a deadline, a price point, a sense that this is the window. In most cases, what feels like now-or-never is actually just now-is-an-option. The pressure is coming from inside the situation, not from the situation itself.',
 action: 'Name what\'s creating the urgency. Then ask if the urgency is actually real.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'A purchase you\'ve been holding off will suddenly feel urgent today. The urgency is not real.',
 },
 {
 id: 'M009',
 teaser: 'You\'ll compare your financial situation to someone else\'s today in a way that\'s inaccurate.',
 full: 'You\'ll get a glimpse of something — someone\'s purchase, their lifestyle, something visible — and a comparison will happen automatically. The comparison will almost certainly be incomplete: their visible output against your full accounting.',
 action: 'Remind yourself comparisons are always partial. Focus on your own trajectory.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'You\'ll compare your finances to someone else\'s today. The comparison will be inaccurate — theirs is always partial.',
 },
 {
 id: 'M010',
 teaser: 'A financial opportunity will have a shorter window than you\'ve been treating it as.',
 full: 'Something you\'ve been mentally holding as “I\'ll get to this when I\'m ready” has an actual closing time that\'s approaching. The opportunity isn\'t going to stay available indefinitely. Treating it as permanent has been convenient but incorrect.',
 action: 'Find out when it actually closes. Then decide with the real information.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'A financial opportunity will have a shorter window than you\'ve been treating it as. Find out when it closes.',
 },
 {
 id: 'M011',
 teaser: 'Someone will make a financial request of you today.',
 full: 'An ask for money, a favor with financial implications, or a request that carries indirect cost will arrive. The answer you give matters less than whether you give the answer you actually mean to give.',
 action: 'Answer the request with what you actually feel, not what\'s easiest to say in the moment.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Someone will make a financial request of you today. Reply with what you actually mean, not the easiest answer.',
 },
 {
 id: 'M012',
 teaser: 'You\'ll realize today you\'ve been paying for something you\'ve been ignoring.',
 full: 'A subscription, a service, a fee that\'s been automatic will come to your attention. The amount it has already cost without you noticing will be the more surprising number than the per-period cost.',
 action: 'Cancel or deal with it today. Don\'t let the guilty feeling make you avoid it again.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'You\'ll realize today you\'ve been paying for something you\'ve been ignoring. Deal with it today.',
 },
 {
 id: 'M013',
 teaser: 'A cheap option now will carry a more expensive cost later.',
 full: 'There\'s a decision where the cheaper path looks like a deal. It will be — or it will be transferring the cost to a later point where it\'ll be harder to manage. The full cost calculation isn\'t just the price tag.',
 action: 'Think through the downstream costs before choosing the cheaper option.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'A cheap option now will carry a more expensive cost later. Calculate full cost, not just upfront.',
 },
 {
 id: 'M014',
 teaser: 'You have an idle asset that will be working for you.',
 full: 'Something you own — a skill, a tool, a space, an account, a relationship — is sitting unused or underdeployed. It has value that isn\'t being extracted. This isn\'t urgent, but it is a quiet waste.',
 action: 'Name one idle asset today. Spend five minutes thinking about one way it will be put to work.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'You have an idle asset that will be working for you. Name it. That\'s the first step.',
 },
 {
 id: 'M015',
 teaser: 'A fear about money is keeping you from a decision that has real upside.',
 full: 'The hesitation on this particular move is motivated by risk aversion, not by the actual numbers. What you stand to protect is less than what you stand to gain if this works. The fear is doing more work than the analysis.',
 action: 'Run the math without the fear assumption. See what it says stripped of the protective narrative.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'A fear about money is keeping you from a decision that has real upside. Run the math without the fear assumption.',
 },
 {
 id: 'M016',
 teaser: 'Your financial stress has a specific source — you\'ve been treating it as general.',
 full: 'The anxiety doesn\'t feel like it has a single cause because you\'re not letting yourself identify one. But it does. One specific number, obligation, or situation is producing most of the weight. Treating it as diffuse keeps it large.',
 action: 'Name the one specific source today. Then make a plan for just that.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'Your financial stress has a specific source you\'ve been treating as general. Name it and address just that.',
 },
 {
 id: 'M017',
 teaser: 'A disciplined choice today will protect you from an urgent one in two months.',
 full: 'The decision in front of you doesn\'t feel important because there\'s no pressure on it right now. But the cumulative effect of this choice, over the next few months, will show up as either a resource or a problem. Today is when it\'s easiest to get right.',
 action: 'Make the disciplined choice today, before the pressure arrives.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A disciplined choice today will protect you from an urgent one in two months. Make it now, before the pressure.',
 },
 {
 id: 'M018',
 teaser: 'Someone owes you money and you\'ve been too polite to bring it up.',
 full: 'Time passing doesn\'t make this easier — it makes it harder. The longer the gap, the more loaded the conversation becomes. What started as a reasonable amount is now carrying relationship weight it didn\'t need to.',
 action: 'Bring it up today. Casually, specifically, soon.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Someone owes you money and you\'ve been too polite to bring it up. The longer you wait, the harder it gets.',
 },
 {
 id: 'M019',
 teaser: 'Your financial plan is operating on assumptions that are no longer accurate.',
 full: 'Income shifted. Priorities changed. Circumstances moved. But the mental model you\'re running your finances from was built some months ago and hasn\'t been updated. You will be optimizing for a target that no longer exists.',
 action: 'Spend 20 minutes today comparing your current reality to your last financial plan.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Your financial plan is operating on outdated assumptions. The target it\'s aimed at will no longer exist.',
 },
 {
 id: 'M020',
 teaser: 'Money and self-image are tangled in a way that will distort a decision today.',
 full: 'A financial choice today isn\'t really about the money — it\'s about how you see yourself or how you want to be seen. The amount is real but the driver is identity. Decisions made from an identity place often produce the wrong financial outcome.',
 action: 'Separate the financial question from the identity question. Answer each on its own terms.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'Money and self-image are tangled in a way that will distort a decision today. Separate the two.',
 },
 {
 id: 'M021',
 teaser: 'An unexpected source of money or value will appear today.',
 full: 'Something will arrive that you weren\'t tracking — a payment, a credit, an opportunity, a referral. The amount will be small or the upside will take time. Notice it. Unexpected income handled well will compound.',
 action: 'When it arrives, don\'t automatically fold it into regular spending. Think about where it should go.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'An unexpected source of money or value will appear today. Decide where it goes before it disappears into spending.',
 },
 {
 id: 'M022',
 teaser: 'A financial goal you\'ve been half-ignoring will demand full attention.',
 full: 'It\'s been running in the background — meant to be a priority but consistently displaced. Today something shifts its position from the periphery to the foreground. Either an opportunity arrives or a cost is becoming visible.',
 action: 'Spend 30 minutes today treating this goal as the primary thing.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'A financial goal you\'ve been half-ignoring will demand full attention today.',
 },
 {
 id: 'M023',
 teaser: 'Someone will suggest you spend money in a way that doesn\'t align with how you actually feel.',
 full: 'Social spending, group decisions, someone\'s recommendation — a purchase will be suggested that sounds reasonable but sits wrong. The right answer is the honest one, not the easy one.',
 action: 'Say what you actually think before agreeing to something you\'ll resent.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'Someone will suggest you spend money in a way that doesn\'t feel right. Say what you actually think.',
 },
 {
 id: 'M024',
 teaser: 'You\'ll want to make a money decision quickly today. Slowing down is right.',
 full: 'The feeling of urgency is real but not well-founded. The purchase, the commitment, the move — it\'ll feel like it needs to happen now. It usually doesn\'t. The urgency is a feature of the situation, not an accurate signal.',
 action: 'If you feel the pressure to decide quickly about money today, take one extra day.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'You\'ll want to make a money decision quickly today. The urgency isn\'t real. Take one extra day.',
 },
 {
 id: 'M025',
 teaser: 'A recurring cost is quietly larger than you\'ve been registering it as.',
 full: 'It barely registers per instance but you\'ve been paying it regularly. Multiplied out, it\'s significantly above your mental number for it. This category of cost hides specifically because each payment feels small.',
 action: 'Add up one recurring cost over a year. The total will reprice it.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A recurring cost is quietly larger than you\'ve been registering it as. Add it up over a year.',
 },
 {
 id: 'M026',
 teaser: 'A financial boundary you\'ve set for yourself will be tested today.',
 full: 'A specific limit — an amount you said you wouldn\'t exceed, a type of expense you said you\'d avoid — will have pressure put on it. The pressure will be real and the reason will be convincing. The boundary is still the right one.',
 action: 'Hold the boundary today. One held line makes the next one easier.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'A financial boundary you\'ve set for yourself will be tested today. Hold it.',
 },
 {
 id: 'M027',
 teaser: 'New information today will change how you think about a financial assumption.',
 full: 'Something you\'ll read, hear, or have confirmed will shift your understanding of a cost, an opportunity, or a financial plan. The new information is accurate. Let it update your model rather than defending the previous one.',
 action: 'If something challenges a financial assumption today, update the assumption.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'New information today will change how you think about a financial assumption. Let it update the model.',
 },
 {
 id: 'M028',
 teaser: 'The price of something will shift between when you last checked and when you decide.',
 full: 'What you mentally priced this at is no longer accurate. Market moved, terms changed, availability shifted. The decision you were about to make was based on a number that\'s no longer current.',
 action: 'Check the actual current price before committing to anything today.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'The price of something will shift between when you last checked and when you decide. Verify before committing.',
 },
 {
 id: 'M029',
 teaser: 'You\'ll spend money today to address a surface problem — not the actual one.',
 full: 'A purchase, a service, a fix — it\'ll address the symptom without touching what\'s actually generating the problem. The money will be spent but the problem will return in a different form.',
 action: 'Before spending on a solution today, ask: is this the actual problem or the visible one?',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'You\'ll spend money today addressing the surface problem, not the actual one. Ask what\'s actually generating it.',
 },
 {
 id: 'M030',
 teaser: 'Today\'s small money choice is setting a pattern, not just solving a moment.',
 full: 'The purchase, the concession, the decision that feels one-time — it\'s establishing a category of decision. Small financial choices made consistently are what financial trajectories are actually built from.',
 action: 'Make today\'s small money choice as if it will be your default going forward. Because it likely will be.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'Today\'s small money choice is setting a pattern, not just solving a moment.',
 },
 {
 id: 'M031',
 teaser: 'A purchase you\'ve been delaying will stop being available at this price soon.',
 full: 'Something real is changing — a price increase, an offer window, a genuine shift in availability. This isn\'t manufactured urgency. The window is actually narrowing.',
 action: 'If you\'ve been considering this genuinely, today is a reasonable day to decide.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'A purchase you\'ve been delaying will stop being available at this price soon. The window is real.',
 },
 {
 id: 'M032',
 teaser: 'A financial conversation today will affect how someone else sees your judgment.',
 full: 'Something about how you handle a money matter — a decision, a request, a response — will be read as a signal about your general financial intelligence. You\'re being assessed, even in a casual exchange.',
 action: 'Be clear, specific, and honest in any financial exchange today.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'A financial conversation today will affect how someone else sees your judgment. Be specific and clear.',
 },
 {
 id: 'M033',
 teaser: 'You\'ll feel more financially stressed today than the actual numbers warrant.',
 full: 'The anxiety will arrive ahead of the actual problem. Your situation is tighter than you\'d like but it is not in crisis. The stress is anticipatory — running possible futures, not the present one.',
 action: 'Write down your actual numbers. Compare them to the feeling. The feeling will be larger.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'You\'ll feel more financially stressed today than the actual numbers warrant. Write down the real numbers.',
 },
 {
 id: 'M034',
 teaser: 'Something you invested in months ago is showing results you haven\'t noticed yet.',
 full: 'A choice you made — money, time, a decision — that felt uncertain or even like a mistake is quietly working. The returns aren\'t dramatic but they\'re visible if you look. You\'ve been looking at other things.',
 action: 'Check in on something you put in place months ago. Look at what\'s actually happened to it.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Something you invested in months ago is showing results you haven\'t noticed yet. Check on it.',
 },
 {
 id: 'M035',
 teaser: 'You\'ll be offered a financial shortcut today. The hidden cost is real.',
 full: 'The offer will be attractive — a deal, a faster path, a way to skip a step. The offer is real but it transfers cost rather than eliminating it. The hidden cost becomes visible later, usually when your options are narrower.',
 action: 'When the shortcut appears, ask specifically: where is the cost going?',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'You\'ll be offered a financial shortcut today. Ask where the cost is going — it doesn\'t disappear.',
 },
 {
 id: 'M036',
 teaser: 'Income you\'ve been expecting will be delayed or adjusted.',
 full: 'Something in your income pipeline is not arriving exactly as planned. A payment delayed, an amount revised, or a decision postponed. This is not permanent but it is a cash flow reality to plan around right now.',
 action: 'Check your two-week cash position against what\'s actually confirmed to arrive.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'Income you\'ve been expecting will be delayed or adjusted. Check what\'s actually confirmed to arrive.',
 },
 {
 id: 'M037',
 teaser: 'The best financial move available to you today costs nothing.',
 full: 'It\'s a subtraction — stopping a payment, cancelling something, saying no, opting out. The most valuable financial decisions are often removing something, not adding it. What can you stop that you haven\'t stopped yet?',
 action: 'Name one financial commitment you should remove. Then remove it today.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'The best financial move available to you today costs nothing. It\'s a subtraction, not an addition.',
 },
 {
 id: 'M038',
 teaser: 'A money pattern you learned from your family is operating in the background.',
 full: 'The anxiety about money, the generosity, the avoidance, the ambition — whatever shaped your family\'s relationship to finances is in your operating system. It runs without you choosing it. Worth knowing which pattern is running today.',
 action: 'Identify one money behavior today that you recognize from your family. Notice whether it\'s serving you.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'A money pattern you learned from your family is operating in the background. Notice which one it is.',
 },
 {
 id: 'M039',
 teaser: 'You\'ve been gathering information about a financial decision for long enough.',
 full: 'The research phase on this has gone on longer than it needed to. You have enough information to decide. More research is providing diminishing returns and is functioning as a way to avoid the discomfort of committing.',
 action: 'Make the financial decision today with what you know.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'You\'ve been gathering information about a financial decision for long enough. You know enough. Decide.',
 },
 {
 id: 'M040',
 teaser: 'The financial milestone you hit deserves recognition that doesn\'t involve spending.',
 full: 'You did something — paid something off, reached a number, cleared something — that matters. The impulse to celebrate by spending is understandable. But the milestone can be marked without a purchase.',
 action: 'Acknowledge the milestone without buying something to mark it.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'The financial milestone you hit deserves recognition that doesn\'t involve spending.',
 },
 {
 id: 'M041',
 teaser: 'A financial goal without a specific number is still just an intention.',
 full: 'You have an intention — saving more, investing, reducing something. It doesn\'t have a specific target or timeline. Without those, there\'s no mechanism for accountability, and the intention stays an intention.',
 action: 'Assign a specific number and a specific date to one financial goal. Write it down.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'A financial goal without a specific number is still just an intention. Give it a number and a date.',
 },
 {
 id: 'M042',
 teaser: 'Supplementary income you\'ve been treating as spending money is building something.',
 full: 'The secondary income — the side work, the extra stream — has more potential than “spending money” treatment gives it. Even moderate supplementary income invested consistently changes the picture materially over two to three years.',
 action: 'Treat the next supplementary income as a building entry, not a spending entry.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Supplementary income you\'ve been treating as spending money is building something if you let it.',
 },
 {
 id: 'M043',
 teaser: 'Something you\'ve been calling expensive is actually good value at its real rate.',
 full: 'There\'s a cost you\'ve been resisting — a service, a tool, a professional — that felt too high. Evaluated per use, per hour, or per actual output delivered, the effective rate will be significantly better than the sticker price implied.',
 action: 'Re-calculate the real per-unit cost of one thing you\'ve been calling expensive.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'Something you\'ve been calling expensive is actually good value at its real rate. Calculate it differently.',
 },
 {
 id: 'M044',
 teaser: 'Urgency around a discount is creating pressure that isn\'t real.',
 full: 'A sale, a limited offer, a countdown — the mechanism is designed to make the decision feel time-constrained. Sometimes the window is real. Often it isn\'t. The urgency is a feature of the offer, not a signal about your actual need.',
 action: 'Before buying because of a deadline, ask whether you\'d buy it at full price. If not, the discount is the product.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'Urgency around a discount is creating pressure that isn\'t real. Ask if you\'d buy it at full price.',
 },
 {
 id: 'M045',
 teaser: 'An investment you made that felt uncertain is about to confirm itself.',
 full: 'Something you put money or time into — a decision that felt shaky, a move that seemed like a risk — is about to deliver a signal. The return will be financial, or it will be information that the decision was right. Either is valuable.',
 action: 'Pay attention to the signal when it comes. Don\'t explain it away.',
 timing: 'You will feel this most before you sleep.',
 shareSnippet: 'An investment you made that felt uncertain is about to confirm itself. Pay attention to the signal.',
 },
 {
 id: 'M046',
 teaser: 'Someone around you is managing money more intelligently than their visible lifestyle suggests.',
 full: 'A person in your orbit looks like they\'re spending at a level you\'d expect. But the full picture is different — they have discipline or a strategy that isn\'t visible from the outside. The visible surface is not the actual financial situation.',
 action: 'Don\'t benchmark to what you can see. Their actual position doesn\'t match their visible one.',
 timing: 'This shows up when you are least distracted.',
 shareSnippet: 'Someone around you is managing money more intelligently than their visible lifestyle suggests.',
 },
 {
 id: 'M047',
 teaser: 'You\'ll want to buy something to feel better today. It\'ll work briefly.',
 full: 'The desire will be real, the item will be real, and the relief will also briefly be real. But relief through purchasing is short-acting. Understanding what you\'re actually managing — stress, boredom, a feeling — does more than the object will.',
 action: 'Notice the feeling before buying. If the feeling is real, address it directly.',
 timing: 'Notice this in the first conversation that matters today.',
 shareSnippet: 'You\'ll want to buy something to feel better today. It\'ll work briefly. Notice what you\'re actually managing.',
 },
 {
 id: 'M048',
 teaser: 'A financial promise someone made to you will either come through or clearly won\'t today.',
 full: 'Something you\'ve been waiting on — a payment, a commitment, a financial follow-through — will resolve itself today. Either the promise lands or it becomes clear that it won\'t on the expected terms.',
 action: 'Have a clear response ready for either outcome. Don\'t let the result drive a reactive financial decision.',
 timing: 'By tonight, this will be clearer.',
 shareSnippet: 'A financial promise someone made to you will either come through or clearly won\'t today. Be ready for either.',
 },
 {
 id: 'M049',
 teaser: 'Now is actually a reasonable time to ask for more.',
 full: 'Whatever the context — a raise, a rate increase, a renegotiation — the conditions are not worse than they were and better than you\'re treating them. Timing always feels uncertain. This is not a worse-than-usual moment.',
 action: 'Initiate a conversation about money with someone who owes you a better arrangement.',
 timing: 'Pay attention to this before the day gets complicated.',
 shareSnippet: 'Now is actually a reasonable time to ask for more. Timing always feels uncertain. This moment is fine.',
 },
 {
 id: 'M050',
 teaser: 'Your current financial position is a snapshot, not a verdict.',
 full: 'What the numbers show today is the result of earlier decisions — some good, some not. It is not a fixed outcome. The decisions being made now are already changing what the snapshot will look like in six months.',
 action: 'Make one decision today that moves your financial snapshot in the direction you want.',
 timing: 'This surfaces by evening.',
 shareSnippet: 'Your current financial position is a snapshot, not a verdict. The decisions being made now are already changing it.',
 },
 {
 id: 'M051',
 teaser: 'You\'re paying for access to something you\'re not using.',
 full: 'A subscription, a membership, a paid account — something you have access to is sitting unused and being automatically billed. The switching cost feels higher than it is. The actual process of cancellation is always shorter than the resistance to it suggests.',
 action: 'Cancel or pause one paid service you haven\'t used this month.',
 timing: 'The signal is strongest in unguarded moments.',
 shareSnippet: 'You\'re paying for access to something you\'re not using. The cancellation takes less time than the resistance suggests.',
 },
 {
 id: 'M052',
 teaser: 'A portion of your spending is functioning as stress management — more than you\'ve acknowledged.',
 full: 'Food delivery, impulse purchases, paid entertainment used as avoidance — some percentage of spending is doing emotional work. This isn\'t inherently wrong. But spending that\'s functioning as stress management should be labeled as such, not tracked as a neutral expense.',
 action: 'Identify what percentage of last week\'s discretionary spending was stress-driven. Just know the number.',
 timing: 'Watch how this plays out after noon.',
 shareSnippet: 'A portion of your spending is functioning as stress management. Know how much. It changes how you see the budget.',
 },
];
