// Mood predictions – 52 entries
// Tone: introspective, grounded, psychologically literate.

export const mood = [
  {
    id: 'D001',
    teaser: 'Something small today may shift your mood more than expected.',
    full: 'You may be carrying more mental load than you realise. Small interruptions, unexpected requests, minor friction — they can feel disproportionately significant when your baseline resilience is already stretched.',
    action: 'Keep things flexible today. Avoid committing to too much before noon.',
  },
  {
    id: 'D002',
    teaser: 'Your energy today is better accessed in short bursts than sustained effort.',
    full: 'You are not in a low state — but you are not in a state that sustains long uninterrupted blocks of output either. The quality of what you produce in focused twenty-minute windows will exceed what comes from grinding through.',
    action: 'Work in focused short intervals today. Rest between them actually.',
  },
  {
    id: 'D003',
    teaser: 'The heaviness you woke up with will not last the day.',
    full: 'There is a weight in the morning that often has nothing to do with anything specific — it is residue from sleep processing, from dreams working through material, from the transition into waking life. It shifts.',
    action: 'Give it until 10am before drawing any conclusions about how today will feel.',
  },
  {
    id: 'D004',
    teaser: 'You are being harder on yourself than the situation warrants.',
    full: 'The internal commentary running right now is applying a standard that you would not apply to anyone else in the same circumstances. The criticism is familiar. That does not make it accurate.',
    action: 'Say to yourself one thing you would say to a close friend in the same position.',
  },
  {
    id: 'D005',
    teaser: 'Restlessness today is a signal, not a personality trait.',
    full: 'The inability to settle — the half-starts, the distraction, the feeling of needing to be somewhere else — is pointing at something unresolved. It is not about your ability to focus. It is about something that needs attention.',
    action: 'Identify the one thing you are avoiding that the restlessness is circling around.',
  },
  {
    id: 'D006',
    teaser: 'Your body is trying to tell you something your mind has been overriding.',
    full: 'Tension in a specific location — shoulders, jaw, stomach — is located there for a reason. The physical register of stress is leading the mental one. The body keeps the score accurately.',
    action: 'Spend five minutes scanning your body. Notice where you are holding. Breathe into that place.',
  },
  {
    id: 'D007',
    teaser: 'Social time today will cost more energy than you want to spend.',
    full: 'Your current state requires more recovery input than usual. Being around people — even people you like — may feel like expenditure rather than replenishment. This is temporary and does not mean anything is wrong.',
    action: 'Protect at least two hours of solitude today. Non-negotiable.',
  },
  {
    id: 'D008',
    teaser: 'A low mood that has been building is close to clearing.',
    full: 'There is something that has been sitting as ambient heaviness — not acute, not addressed, just present. It has been there long enough to feel normal. It is about to shift, not because circumstances change but because processing completes.',
    action: 'Do not force the clearing. Just be willing to let it go when it comes.',
  },
  {
    id: 'D009',
    teaser: 'You are more emotionally resourced today than you have been recently.',
    full: 'Something has refilled — sleep, a good conversation, a moment of connection, a thing completed. The internal level is higher than it has been. This is a window for things that require emotional access.',
    action: 'Use this window for something that requires you to be present, not just productive.',
  },
  {
    id: 'D010',
    teaser: 'Comparison is actively degrading your state right now.',
    full: 'You have been measuring your internal experience against someone else\'s external appearance. The measurement is not real — you are comparing your most private self to their most public self. The comparison is structurally unfair.',
    action: 'Step off the comparison for the rest of today. Mute, close, or redirect.',
  },
  {
    id: 'D011',
    teaser: 'The irritability you are feeling is not about its apparent cause.',
    full: 'Something is producing an internal friction that has attached itself to the nearest available target — a task, a person, a situation. That target is not the source. The source is something older or deeper.',
    action: 'Before reacting today, pause and ask: what is this actually about?',
  },
  {
    id: 'D012',
    teaser: 'You are in a period of transition that looks like stagnation from the inside.',
    full: 'When things are shifting internally — identity, direction, value priorities — the external life can look still. But stillness is not the same as stuck. There is significant internal movement that has no visible metric yet.',
    action: 'Trust the internal process even when nothing visible is changing.',
  },
  {
    id: 'D013',
    teaser: 'Rest you defer now returns as cost later this week.',
    full: 'There is a pattern where the urgency of the current demands defers recovery, and two days later the performance drops, the mood darkens, and the cost of the deficit becomes visible. The math is consistent.',
    action: 'Go to bed thirty minutes earlier than usual tonight.',
  },
  {
    id: 'D014',
    teaser: 'Anxiety is running as background process and affecting foreground decisions.',
    full: 'There is an underlying hum of worry — not acute, not specific in this moment — that is affecting how you read situations and how you respond to people. You may not be aware of the level it is running at.',
    action: 'Name the specific underlying worry. Even partially. Naming reduces the background load.',
  },
  {
    id: 'D015',
    teaser: 'A moment of genuine laughter today will clear more than it should be able to.',
    full: 'There is a weight-to-laughter exchange rate that is especially favorable right now. One real moment of humor — not performed, but genuinely felt — resets something in the nervous system.',
    action: 'Find or create one moment of genuine levity today. It matters more than you might grant it.',
  },
  {
    id: 'D016',
    teaser: 'You are processing something that will take longer than today.',
    full: 'There is a thing — an experience, a change, a loss, a shift — that is being integrated over time and cannot be rushed. What you are feeling is the process working, not something being wrong.',
    action: 'Allow the processing. Give yourself the duration it needs.',
  },
  {
    id: 'D017',
    teaser: 'Movement of any kind today will improve everything else.',
    full: 'The body in its current state is contributing to the mental state. Not dramatically — just quietly making things heavier. Any movement — a walk, stretching, stairs instead of the lift — improves the register.',
    action: 'Move your body for twenty minutes before anything else today.',
  },
  {
    id: 'D018',
    teaser: 'The version of yourself you are being hardest on does not deserve it.',
    full: 'There is a period — recent or ongoing — where you did not operate at your best. You made choices that were not ideal, or fell short of your standards, or hurt someone. The punishing is not proportionate to the transgression.',
    action: 'Acknowledge the thing, own it genuinely, and then put it down.',
  },
  {
    id: 'D019',
    teaser: 'Your focus is scattered because your intention for the day is unclear.',
    full: 'When there is no specific thing that today is for — no primary direction — attention distributes across everything and sinks into nothing. The scattered feeling is a symptom of missing purpose, not a flaw.',
    action: 'Name one thing today is for. One. Not three.',
  },
  {
    id: 'D020',
    teaser: 'Overstimulation from the last 48 hours is catching up with you.',
    full: 'Information, interaction, decision-making, noise — the input volume recently has exceeded the processing capacity. The cognitive fog or flat affect you feel now is recovery, not failure.',
    action: 'Reduce input for the next few hours. Quiet is the medicine.',
  },
  {
    id: 'D021',
    teaser: 'There is a specific person whose energy is affecting yours more than you notice.',
    full: 'Someone in your regular orbit carries a quality — anxiety, negativity, urgency, heaviness — that transfers to you without announcement. You absorb it as your own state without locating the source.',
    action: 'Notice how you feel before and after specific interactions today.',
  },
  {
    id: 'D022',
    teaser: 'Productivity is not the right metric for today.',
    full: 'You may feel the pull to justify the day through output. But the internal state needs something different today — rest, reflection, connection, or simply the permission to be less efficient than usual.',
    action: 'Remove output as the metric for today. Replace it with how you treat yourself and others.',
  },
  {
    id: 'D023',
    teaser: 'A creative energy that has been dormant is available right now.',
    full: 'Something has cleared — a pressure, an obligation, a preoccupation — and there is an opening in the mental space that often hosts creative thought. This window does not last long.',
    action: 'Use the next two hours for something that actually interests you, not something that needs doing.',
  },
  {
    id: 'D024',
    teaser: 'The resistance to beginning is larger than the difficulty of the thing itself.',
    full: 'The task is not as hard as the procrastination makes it feel. What you are experiencing is dread, not difficulty. Once started, the task will be demonstrably easier than the feeling predicted.',
    action: 'Start the thing you have been putting off. You will feel this was true within ten minutes.',
  },
  {
    id: 'D025',
    teaser: 'Gratitude for something real will reframe the next few hours.',
    full: 'Not the performed gratitude, not the list-making exercise — but one genuine noticing of something specific and real that is good in your life right now. It creates a chemical shift that is not trivial.',
    action: 'Name one specific real thing that is good. Not a general thing. Something specific to today or this week.',
  },
  {
    id: 'D026',
    teaser: 'Something you told yourself you were over is not fully over.',
    full: 'There is a matter — a grievance, a loss, a transition, a relationship chapter — that you have declared resolved in your narration of yourself. It is not fully resolved. The emotion returned today proves this.',
    action: 'Give it one more honest hour of attention instead of bypassing it again.',
  },
  {
    id: 'D027',
    teaser: 'Sleep quality is doing more to your mood than any external event.',
    full: 'The emotional tone of today — the low patience, the blunted enthusiasm, the ambient pessimism — is largely a function of insufficient or disrupted sleep. It is not a signal about your life. It is a signal about rest.',
    action: 'Do not make any significant decisions today that you could make tomorrow after sleeping.',
  },
  {
    id: 'D028',
    teaser: 'An unexpected encounter today will briefly but genuinely lift your state.',
    full: 'There will be a moment — a conversation, a shared laugh, an unexpected kindness — that provides a real if temporary lift. Do not dismiss it as small. Let it land properly.',
    action: 'Be more present in encounters today than you usually allow yourself to be.',
  },
  {
    id: 'D029',
    teaser: 'Saying no to one thing today will improve your state for everything else.',
    full: 'There is something in your day that is optional and would cost you more than it would give. The energy you would spend on it would improve all your other activities if it stayed in the system.',
    action: 'Identify what is optional and decline it.',
  },
  {
    id: 'D030',
    teaser: 'You are operating in a state of low-grade depletion that has become background.',
    full: 'The depletion has existed long enough that it has become the reference normal. You are not crashing — but you are performing at a lower baseline than your actual capacity. The gap is invisible because the depletion is invisible.',
    action: 'What would three full days of real recovery look like? Name what would be in that period.',
  },
  {
    id: 'D031',
    teaser: 'Anger you have been managing with effort is close to the surface today.',
    full: 'There is a justified frustration that you have been containing because the time or place was not right. Today it is closer to the edge. It is not wrong to feel this — but it needs a better outlet than the nearest person.',
    action: 'Name the real source of the frustration before you are in the situation where it might surface.',
  },
  {
    id: 'D032',
    teaser: 'Nostalgia today is a signal about something missing in the present.',
    full: 'When the past feels particularly vivid and good, it is often because the present is missing a quality that the past had — a sense of possibility, a belonging, a simplicity. The nostalgia is pointing at a current need.',
    action: 'What quality is the nostalgia pointing at? How could you get more of that now?',
  },
  {
    id: 'D033',
    teaser: 'Your intuition about a current situation is more reliable than your reasoning.',
    full: 'You have a sense about something — a person, a decision, a direction — that your logical mind keeps countermanding. But the logical frame may be built on assumptions that the intuition is seeing past.',
    action: 'Write down what your gut says. Then separate that from the arguments against it.',
  },
  {
    id: 'D034',
    teaser: 'The need to be seen and acknowledged is present today.',
    full: 'This is not vanity or weakness — it is a basic human need at elevated intensity right now. The need that is unacknowledged does not disappear. It just comes out sideways.',
    action: 'Find a way to meet this need directly today, rather than hoping someone notices.',
  },
  {
    id: 'D035',
    teaser: 'A period of sustained pressure is approaching its natural end.',
    full: 'There has been an extended stretch of intensity — work, relationship stress, financial pressure, or all three. The weight has been real. There is evidence that this sustained period is close to completing.',
    action: 'Identify what after this period looks like. Give your nervous system something to anticipate.',
  },
  {
    id: 'D036',
    teaser: 'You have not laughed at yourself recently. That is a sign of something.',
    full: 'The ability to find oneself absurd — to notice when you are being particularly driven, anxious, or serious — is a form of resilience. Its absence means the seriousness has become total. That is oxygen-depleting.',
    action: 'Find something genuinely funny about your current situation. It is there.',
  },
  {
    id: 'D037',
    teaser: 'The story you are telling yourself about why you feel this way may be wrong.',
    full: 'You have assigned a cause to your current emotional state — a specific person, situation, or event. But the state may have a different or more complex origin. The assigned cause may just be the most recent or most visible thing.',
    action: 'Ask: is this feeling actually about what I think it is about?',
  },
  {
    id: 'D038',
    teaser: 'A completion is available today that has been waiting.',
    full: 'There is something unfinished — not large, but persistent — that is consuming a small amount of mental energy every day in the background. Finishing it today would free that energy for actual use.',
    action: 'Finish the small incomplete thing. Today.',
  },
  {
    id: 'D039',
    teaser: 'Being kinder to a stranger today will help you more than it helps them.',
    full: 'The act of genuine, unprompted kindness to someone you do not know and will not see again produces a lasting uplift in the giver that is disproportionate to the effort. The science is consistent on this.',
    action: 'Find one person today who benefits from a small, unsolicited act of kindness.',
  },
  {
    id: 'D040',
    teaser: 'The urgency you feel is manufactured by your own expectations.',
    full: 'The pressure of right now is not external — it is a self-imposed timeline, a standard, a fear of falling behind. The urgency is real as a feeling. Its necessity is less certain.',
    action: 'Ask: who says this has to happen today? Is that answer actually true?',
  },
  {
    id: 'D041',
    teaser: 'Your capacity for joy today is higher than your willingness to access it.',
    full: 'The infrastructure is there — the conditions are present, the people are available — but there is a habitual seriousness that keeps the uptake lower than it could be. Permission is the missing ingredient.',
    action: 'Give yourself permission to feel good today, specifically and deliberately.',
  },
  {
    id: 'D042',
    teaser: 'Isolation is making a smaller problem feel like a larger one.',
    full: 'The thing that is sitting on you would reduce significantly if it were shared with someone appropriate. It is not a problem that requires solving — it just requires being witnessed. That alone changes its weight.',
    action: 'Tell one person about the thing you have been carrying alone.',
  },
  {
    id: 'D043',
    teaser: 'The afternoon will be qualitatively different from the morning.',
    full: 'Whatever the morning brings — heaviness, difficulty, low energy — there is a shift point around midday that often resets the register. Do not write the day off based on its opening hours.',
    action: 'Reserve judgement about today until at least 2pm.',
  },
  {
    id: 'D044',
    teaser: 'A habit that usually grounds you has gone missing lately.',
    full: 'There is a practice — exercise, journaling, a particular kind of social contact, a creative outlet — that consistently regulates your state and that you have let lapse in recent weeks. The absence is contributing to the current texture.',
    action: 'Reinstate the practice today. Even at a fraction of the usual scale.',
  },
  {
    id: 'D045',
    teaser: 'The thing most likely to reset your state is the thing you are most resistant to.',
    full: 'When resistance to a specific activity is highest, it is often because that activity would address the underlying state most directly. The aversion and the medicine are frequently the same thing.',
    action: 'Do the specific thing you are most resisting today.',
  },
  {
    id: 'D046',
    teaser: 'You are holding more than is yours to hold.',
    full: 'There are worries, problems, and emotional weights in your system that belong to other people and that you are carrying alongside your own. This is care. It is also a leak.',
    action: 'Identify one thing you are carrying that is not yours. Set it down consciously.',
  },
  {
    id: 'D047',
    teaser: 'Clarity about what you actually want would improve your mood significantly.',
    full: 'Much of the ambient dissatisfaction comes not from having the wrong things but from not knowing what you actually want. Undefined desire is experienced as general unfulfillment.',
    action: 'Name one thing you genuinely want for this week. Then take one concrete step toward it.',
  },
  {
    id: 'D048',
    teaser: 'Being good at managing your emotions is making you less visible to people who care.',
    full: 'Your ability to regulate well means the people close to you may not know when you are struggling. This protects the relationship from day-to-day turbulence but also creates a distance when you need support.',
    action: 'Let one person see a little more of what is actually happening.',
  },
  {
    id: 'D049',
    teaser: 'The peak window for your best thinking today has not happened yet.',
    full: 'Depending on your biology and current sleep, there is a period — possibly this afternoon — where your cognition will be clearer and your emotional noise lower. Reserve your most important thinking for that window.',
    action: 'Do not attempt your hardest thinking before your energy peak. Note when it arrives.',
  },
  {
    id: 'D050',
    teaser: 'Acceptance of a specific thing would remove a significant drainage.',
    full: 'There is something you are spending internal energy on — resisting its reality, negotiating with it, being angry at it. The acceptance of that one thing does not mean agreement with it. It means you stop fighting what is already true.',
    action: 'Name the thing. Then try: this is what is true right now. And breathe.',
  },
  {
    id: 'D051',
    teaser: 'You are more resilient than recent events have made you feel.',
    full: 'Events have been demanding. The coping has been effortful. It is easy to interpret this as fragility. The actual evidence is the opposite — you have continued to function through conditions that are not easy.',
    action: 'Name three things you have handled in the last month that were genuinely difficult.',
  },
  {
    id: 'D052',
    teaser: 'A moment of stillness today will do more than a full day of managing.',
    full: 'You have been managing — responding, adapting, handling, producing. The rate of management has exceeded the rate of restoration. Today\'s highest-value activity may simply be to stop for long enough to let things settle.',
    action: 'Find fifteen minutes today with no input — no phone, no music, no agenda. Sit in that.',
  },
];
